### ISSUE TITLE
Help with themes on mobile devices.

### ISSUE THREAD

**Issue by raulsperoni** [TheCoder4eu/BootsFaces-OSP#312] opened 2016-02-26 11:24 UTC
Hi i'm using primefaces 5.3 and bootsfaces 0.8.1, i've applied "paper" theme and looks good in big screens, but all the content between bootsfaces tags looks really small on small screens, almost unreadable without zooming in. Is there anything i'm doing wrong? 
![phne](https://cloud.githubusercontent.com/assets/8474238/13350976/4f5ed042-dc62-11e5-82c9-46d2feaad698.png)
Thanks a lot!

**Comment by raulsperoni** [comment] 2016-02-26 19:12
Te solution was adding 
`<meta name="viewport" content="width=device-width, initial-scale=1">`
in head.

Thanks

**Comment by stephanrauh** [comment] 2016-02-26 19:19
@TheCoder4eu Is this something we've forgotten to document? Or should BootsFaces render this `meta` tag by default?

**Comment by raulsperoni** [comment] 2016-02-26 19:49
I should add that i could not get the theme applied until i added     `<link id="currentCSS" rel="stylesheet" type="text/css" href="https://bootswatch.com/paper/bootstrap.min.css"/>` so maybe i am doing something wrong.

**Comment by stephanrauh** [comment] 2016-04-19 21:22
This issue is a duplicate of #336, which has been solved in the meantime. The meta tag now is added automatically to each JSF page.

**Closed by stephanrauh** 2016-04-19 21:22 UTC
Labels: enhancement, verifying issue
