### ISSUE TITLE
PrimeFaces is not defined. possible incompatibility with bootsfaces?

### ISSUE THREAD

**Issue by sergio11** [TheCoder4eu/BootsFaces-OSP#537] opened 2016-11-01 18:50 UTC
Hi,
I have a problem when use primefaces (5.3) on my project with bootsfaces (0.9.2-SNAPSHOT).
In the javascript console gives the following error when using the component p: chart:

![error_primefaces](https://cloud.githubusercontent.com/assets/6996211/19902249/405d4e76-a06a-11e6-8d39-c96ce2f0523f.PNG)

As it stated in the PrimeFaces' s documentation I have included the element h: head of JSF2 and the namespace in the html element:

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:head>
        <title>#{i18n['page.title']}</title>
    </h:head>
```
I have defined the following context parameters

```
<context-param>
      <param-name>javax.faces.PROJECT_STAGE</param-name>
      <param-value>Development</param-value>
  </context-param>
 <context-param>
      <param-name>BootsFaces_THEME</param-name>
      <param-value>cyborg</param-value>
 </context-param>
 <context-param>
     <param-name>primefaces.THEME</param-name>
     <param-value>bootstrap</param-value>
 </context-param>
```

I have seen that in the document header has not included any js script Primefaces:

![header](https://cloud.githubusercontent.com/assets/6996211/19902676/f5645700-a06b-11e6-809b-695b9d4b517d.PNG)

The code which gives the proble is this:

```

<h:form rendered="#{topicsManagedBean.totalTopics gt 0}">
            <b:row>
                <b:inputText 
                    placeholder="#{i18n['page.results.tags.placeholder']}"
                    value="#{topicsManagedBean.topicsSelected}"
                    tags="true"
                    typeahead="true"
                    typeahead-highlight="true"
                    typeahead-limit="10"
                    typeahead-values="#{topicsManagedBean.topicsCSV}"
                    onchange="ajax:chartBean.update()"
                    update="@form:topicsResults, :alerts"
                    tooltip="#{i18n['page.results.tags.tooltip']}"
                    tooltip-position="left">
                    <f:converter converterId="tagsConverter" />
                    <f:facet name="prepend">
                        <b:iconAwesome name="search" />
                    </f:facet> 
                </b:inputText>
            </b:row>
            <b:row  id="topicsResults">
                <b:messages />
                <b:panelGrid colSpans="6,6" size="md" rendered="${not empty topicsManagedBean.topicsSelected}" style="margin-top: 1rem">
                    <c:forEach var="topic" items="#{topicsManagedBean.topicsSelected}">
                        <b:panel span="6" title="Result for topic #{topic}" collapsible="false" look="info">
                            <b:row>
                                <p:chart type="donut" model="#{chartBean.donutCharts.get(topic)}" style="width:70%;height:300px;margin: 0 auto;" />
                            </b:row>
                            <b:row>
                                <p:chart type="pie" model="#{chartBean.pieCharts.get(topic)}" style="width:70%;height:300px;margin: 0 auto;" />
                            </b:row>
                        </b:panel>
                    </c:forEach>
                </b:panelGrid>
            </b:row>
        </h:form>
```
you know if it has anything to do with bootsfaces?
thanks :)

**Comment by stephanrauh** [comment] 2016-11-01 20:14
I've seen a similar problem with PrimeFaces 6.0, but that's because the split the PrimeFaces.js into two files starting with 6.0. So that's not the reason in your case. It might have to do something with the `rendered` tag. Until version 5.3, PrimeFaces didn't add resources in an AJAX request, so if you start with `rendered="false"` and set it to `rendered="true"` in a subsequent AJAX call, this is the error I'd expect. Is that your scenario?

Another idea: add an `p:inputText` (or something like that) to the form and see if it changes anything. Maybe it's a bug of the chart component.

**Comment by sergio11** [comment] 2016-11-01 21:12
thanks for answering.

When I add the component p: input the error does not occur.
What does this mean?

**Comment by stephanrauh** [comment] 2016-11-02 08:22
This means that this might be a PrimeFaces bug. PrimeFaces needs to declare the required resources for every component. Sometimes a commonly used file gets lost in this list (because it's requested by other PF components). But before reporting it to the PrimeFaces guys, I'd like to double-check it.

**Comment by zhedar** [comment] 2016-11-17 09:57
I also think, that this is a PrimeFaces thing, we only had problems with resource order, therefore producing JavaScript errors like `Can't find variable: PrimeFaces`, but we wouldn't omit any resources at all.
Have you tried to update to PF 6.0?

**Comment by sergio11** [comment] 2016-11-17 10:20
If I upgrade to primefaces 6 I get other errors and I had to use version 5.3. But if there is any component of Primefaces in the view that is not constructed conditionally (c: if). It works well

**Comment by zhedar** [comment] 2016-11-19 21:10
Did you try to reproduce this error in a simple project without BootsFaces? If it's not related to us, I would recommend to post it over at [PrimeFaces](https://github.com/primefaces/primefaces/issues) and we can close this issue.

**Comment by stephanrauh** [comment] 2017-01-15 20:33
This bug probably has been caused by a change in PrimeFaces 6.0. They split the PrimeFaces.js in two files, the core.js and a second file. The original include statement don't work anymore.

**Closed by stephanrauh** 2017-01-15 20:33 UTC
Labels: verifying issue, Waiting for user answer
