### ISSUE TITLE
Enhancement: RTL Support

### ISSUE THREAD

**Issue by xystra** [TheCoder4eu/BootsFaces-OSP#99] opened 2015-06-02 13:58 UTC
I'm not sure (search came up null) if this has been discussed or considered but RTL support would be a big + . What are the plans for providing RTL support?

**Comment by TheCoder4eu** [comment] 2015-06-02 14:13
Hi,
at present we were concentrating our efforts in other directions but I agree it would be a great feature to have.
However, Bootstrap 3.x does not support RTL, but I stumbled upon a project that aims to fill this gap:

https://github.com/morteza/bootstrap-rtl

We'll have a look at it and see how easy would be to add it to our project.

**Comment by stephanrauh** [comment] 2016-01-06 22:05
Duplicate of #216 and #228. I've implemented RTL support a couple of days agao.

**Closed by stephanrauh** 2016-01-06 22:05 UTC
Labels: enhancement, under consideration
