### ISSUE TITLE
colorpicker component

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#290] opened 2016-02-11 17:49 UTC
Hello All,

Plan you a colorpicker component implementation?
I've found a good and looks easy to implement tool for bootsfaces colorpicker.

http://labs.abeautifulsite.net/jquery-minicolors/

What do you think about it?

Best Regards,
Mihaly

**Comment by zhedar** [comment] 2016-04-12 12:42
To track progress on this: This seems to be implemented in https://github.com/TheCoder4eu/BootsFaces-OSP/pull/313 by @asterd .

**Comment by stephanrauh** [comment] 2016-04-19 21:28
The new colorpicker component has been implemented, but it hasn't been documented yet.

**Comment by stephanrauh** [comment] 2016-04-19 21:29
@asterd Would you mind to add a documentation page to our showcase?

**Comment by asterd** [comment] 2016-04-20 06:30
I've already done it. you can find here: http://www3.bootsfaces.net/Showcase/forms/ColorPicker.jsf

**Comment by stephanrauh** [comment] 2016-04-20 07:07
THX! The demo looks a bit odd on a smartphone because the screen scrolls when selecting the color. After fixing this we can close the issue. It's a simple meta tag setting (or something like that).

**Comment by asterd** [comment] 2016-04-20 13:09
@stephanrauh i've tried the colorpicker showcase on my smartphone but i don't understand where is the problem. The screen scroll when you focus on component because it is an input so the keyboards pops out. If we want to prevent this, it means that on smartphone, you cannot write by hand the color.. is this the desired behaviour?

**Comment by stephanrauh** [comment] 2016-04-20 20:20
I thought of these two settings:
```xml
<meta name="viewport" 
  content="width=device-width, initial-scale=1.0, user-scalable=no">
```
```Javascript
document.body.addEventListener('touchmove', function(event) {
  event.preventDefault();
}, false); 
```
Read the full story here: http://www.html5rocks.com/en/mobile/touch/

**Comment by stephanrauh** [comment] 2016-04-20 22:07
I've added the preventDefault() bit to the component, but it seems to be to thorough on my smartphone. Now the entire page doesn't scroll on swipe. Maybe a caching problem?

**Comment by zhedar** [comment] 2016-04-20 22:15
Can confirm, can't scroll anymore on the iPhone although I could today morning. How should this be related to caching?

**Comment by stephanrauh** [comment] 2016-04-20 22:44
So my change doesn't work as local as I hoped. Need to investigate the swipe problem with the color selector more thorough. Swipe should scroll the page - except for swiping on the color wheel, which should chose another color.

**Comment by asterd** [comment] 2016-04-21 06:34
@stephanrauh the problem seems related to the page zoom. If you try the color picker component in the page at his initial size, the touch works good... but if you zoom the page, the touch does not work and it creates the problem.. Maybe is an issue with the jquery plugin.. i'll try to investigate ok?

**Comment by asterd** [comment] 2016-04-21 07:18
Ok.. this seems to be a spread problem that can be solved with only the meta viewport tag.
In particular, the setting that @stephanrauh  suggest 

```xml
<meta name="viewport" content="width=device-width, initial-scale=1.0, 
           maximum-scale=1.0, user-scalable=no" />
```

is the only solution in this case. The problem is related to the component rendering: after a page zoom, it does not recalculate position and touch offset. 
So, we have to document that the page with colorpicker must have this setting to prevent touch problems..

**Comment by stephanrauh** [comment] 2016-04-21 18:34
Ah, now I understand why you didn't get my description. I didn't use a simple touch gesture to select the column. I touched and started to move my finger. This swipe did something useful with the color selector - but at the same time, it made the entire page scroll away. It would be good to prevent page scrolling as long as the finger touches the color picker. Outside the color picker, the page should scroll.

**Comment by stephanrauh** [comment] 2016-04-21 19:17
Now it works fine.

**Comment by stephanrauh** [comment] 2016-04-21 19:21
Added the last missing piece of the documentation.

**Closed by stephanrauh** 2016-04-21 19:21 UTC
Labels: documentation, enhancement, new fwk component
