### ISSUE TITLE
JSF1091: No mime type could be found for file null.  To resolve this, add a mime-type mapping to the applications web.xml.

### ISSUE THREAD

**Issue by abraham1980** [TheCoder4eu/BootsFaces-OSP#1155] opened 2020-09-26 17:19 UTC
hi, im getting this error, on fresh proyect. I run on payara 5 and tomme 8
bootsfaces version 1.5.0

26-Sep-2020 19:13:20.173 WARNING [http-nio-8080-exec-7] com.sun.faces.context.ExternalContextImpl.getMimeType JSF1091: No mime type could be found for file null.  To resolve this, add a mime-type mapping to the applications web.xml.

The page to reproduce: 

```xml
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
        <h:form>
        <b:commandButton value="boton" update="@this"/> <br/>
        
        </h:form>
    </h:body>
</html>
```
is related to de update field

**Comment by stephanrauh** [comment] 2020-09-26 18:29
I don't think this bug has anything to do with BootsFaces. Maybe the error message is correct. Have you registered the *.xhtml files with the FacesServlet?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">
  
   ...

    <servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.jsf</url-pattern>
    </servlet-mapping>
</web-app>

**Comment by abraham1980** [comment] 2020-09-27 17:28
I did:

<?xml version="1.0" encoding="UTF-8"?>
<web-app version="4.0" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd">

...
<servlet>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>


anyway it dont broke anything just log

**Comment by stephanrauh** [comment] 2020-09-27 17:42
Which URL are you using? If you configure your FacesServlet like so, it shows the `index.xhtml` when you navigate to `http://localhost:8080/index.xhtml`.

**Comment by klease** [comment] 2021-01-27 20:56
I also have the error  "com.sun.faces.context.ExternalContextImpl#798 - JSF1091: No mime type could be found for file null...."
I'm using In Mojarra 2.3.14.
It occurs in a <b:dataTable> element with an Ajax onselect handler "onselect="ajax:listBean.onSelect(entity, typeOfSelection, indexes)".
Selecting a row in the table causes a POST request to trigger the onSelect() method which works correctly. 
By putting a breakpoint at the line mentioned in the message, I identified the cause.
During the rendering phase, all the resources in the viewRoot are processed in PartialViewContextImpl.renderComponentResources().
The error message appears once for each "special" bootsfaces resource, for example when the resource is a net.bootsfaces.listeners.InternalIE8CompatiblityLinks object.
It was also occurring on the dataTables-related js and css which were fetched from the CDN. By forcing those to be retrieved locally, the warning for those resources disappeared.
I agree it's just a warning if the project is in development stage, but it's rather annoying and misleading.

**Comment by macbl** [comment] 2021-02-14 18:00
Yes, it would be nice if there would be a fix for this (not using the CDN is a rather drastic measure)

**Comment by geopossachs** [comment] 2021-10-17 15:48
About this PR I think the error comes from a missing type = "text / javascript" tag in InternalIE8CompatiblityLinks

https://github.com/TheCoder4eu/BootsFaces-OSP/blob/4678f401998430f4386f6c347037c3c3d6a1bdfa/src/main/java/net/bootsfaces/listeners/InternalIE8CompatiblityLinks.java#L62

https://github.com/TheCoder4eu/BootsFaces-OSP/pull/1173

**Comment by geopossachs** [comment] 2021-10-18 19:58
found the point of the log message

**Comment by stephanrauh** [comment] 2024-08-12 15:47
I'm afraid development of BootsFaces has slowed down considerably. We'll never manage to address this issue. Let's close it.

**Closed by stephanrauh** 2024-08-12 15:47 UTC
