### ISSUE TITLE
Documentation on the Main Site is Broken

### ISSUE THREAD

**Issue by mfreeman-xtivia** [TheCoder4eu/BootsFaces-OSP#1154] opened 2020-09-19 12:03 UTC
None of the links for component documentation in the left sidebar work on the main site.

They seem to be missing the host portion of the URL somehow

**Comment by exabrial** [comment] 2020-10-07 21:43
+1. If there's anything I could do to help out this please let me know. I'd be happy to get involved

**Comment by exabrial** [comment] 2020-10-07 21:44
just noticed this is a duplicate of #1150

**Comment by vsvetoslavov** [comment] 2020-10-23 07:11
@mfreeman-xtivia They seem to not work even if you add the host portion by hand...

**Comment by geopossachs** [comment] 2021-01-10 11:49
#1161

**Comment by stephanrauh** [comment] 2024-08-12 15:53
The showcase seems to work again.

**Closed by stephanrauh** 2024-08-12 15:53 UTC
