### ISSUE TITLE
Unable to find resource bsf, css/default/icons.css

### ISSUE THREAD

**Issue by douglasjunior** [TheCoder4eu/BootsFaces-OSP#328] opened 2016-03-15 14:53 UTC
Error: Unable to find resource bsf, css/default/icons.css

Problem appears in version 0.8.1, `icons.css` is in different place.
![captura de tela 2016-03-15 as 11 49 59](https://cloud.githubusercontent.com/assets/1512341/13782003/1c00f220-eaa4-11e5-907f-f45d7d1d40e4.png)

In the previous version that does not exist.
![captura de tela 2016-03-15 as 11 27 42](https://cloud.githubusercontent.com/assets/1512341/13782058/5088e016-eaa4-11e5-8588-75f081b6e17d.png)

My `pom.xml`:
```xml
        <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>5.3</version>
        </dependency> 
        <dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>4.0.0</version>
        </dependency> 
        <dependency>
            <groupId>org.primefaces.themes</groupId>
            <artifactId>bootstrap</artifactId>
            <version>1.0.9</version>
        </dependency>
        <dependency>
            <groupId>net.bootsfaces</groupId>
            <artifactId>bootsfaces</artifactId>
            <version>0.8.1</version>
        </dependency>  
```

**Comment by TheCoder4eu** [comment] 2016-03-19 16:15
Yes the icons.css is common to all Themes.

Could you please tell where do you see the 
"Error: Unable to find resource bsf, css/default/icons.css"
error?

It is in the browser or in your Application Server log?

**Comment by stephanrauh** [comment] 2016-03-19 20:08
I've seen similar messages, too. They appear in the application server log. I wonder if this happens only in the Maven build of BootsFaces?

**Comment by douglasjunior** [comment] 2016-03-19 20:41
I see in `<p:messages />`.

When I load page first time the message not happens. But, if I try login with wrong passaword, I show the error message for user.

With my error message appers: `"Error: Unable to find resource bsf, css/default/icons.css"`

Se eu remover os BootsFaces, a mensagem não ocorre.

**Comment by stephanrauh** [comment] 2016-03-19 20:46
When you say you see it in `prime:messags`, you mean it's a message shown to the user? A message that's rendered as part of the HTML page?

**Comment by douglasjunior** [comment] 2016-03-19 21:10
Yes.

**Comment by p694230** [comment] 2016-03-20 21:39
Unable to find .css file

![erro001](https://cloud.githubusercontent.com/assets/16191384/13907346/e334fec0-eeca-11e5-9908-d8a499ea6f4b.PNG)

File of .jar
![rep_001](https://cloud.githubusercontent.com/assets/16191384/13907348/e33b8e20-eeca-11e5-83bd-98e494aae59b.JPG)

Error using theme 
![theme_carulean](https://cloud.githubusercontent.com/assets/16191384/13907347/e3399c1e-eeca-11e5-8bb1-e4bda6367791.JPG)

**Comment by guitoneloto** [comment] 2016-03-20 23:02
A few months ago I had solved the problem above , now tive to do the project again . I remember that in the mentioned site on the configuration with OmniFaces , the site was changed and now only have a section talking about the configuration . It would be possible to provide the old configuration ?

**Comment by stephanrauh** [comment] 2016-03-22 21:36
@guitoneloto It's all on GitHub. I suppose you'll find the information that's gone missing quickly on https://github.com/TheCoder4eu/BootsFacesWeb/commits/master/src/main/webapp/integration/OmniFaces.xhtml. Please report back when you've found the missing piece of information, so we can restore it for the benefit of other readers. 

Thanks in advance!
Stephan

**Comment by zhedar** [comment] 2016-03-22 23:49
I've encountered the same problem with 0.8.1 a while ago and tried to upgrade again just now. 
I'm also using Maven, but I also tried to drop the downloadable jar from the bootsfaces page directly into the project yielding the same problem. Unless that artifact was build with mvn as well, I don't think that's the problem.

Also using OmniFaces (tried all 2.x versions, currently running 2.3-RC1) by default without the `CombinedResourceHandler`. If I'm actually trying to use that handler, the whole resources won't load anymore, rendering the site unusable. But that's just triggered by the missing resource in the first place.

I think @stephanrauh can handle the german log message, although it won't help much:

    Ressource css/default/icons.css aus Bibliothek bsf kann nicht gefunden oder bedient werden.
    CombinedResourceHandler: The resource bsf:css/default/icons.css cannot be found and therefore a 404 will be returned for the combined resource ID ...

**Comment by zhedar** [comment] 2016-03-23 00:44
As @guitoneloto pointed out, `icons.css` is currently located under `bsf/css`. It seems like it is currently needed in both `bsf/css/default` and `bsf/css`. I fixed the problem by copying the `icons.css` under `bsf/css/default` as well.
But now I got an regression to 0.8.0: getting 3 404s with `glyphicons-halflings-regular` again.

**Comment by stephanrauh** [comment] 2016-03-24 21:26
Just managed to reproduce the problem. I pushed it to the BootsFacesWeb repository as issues/issue328.xhtml.

![image](https://cloud.githubusercontent.com/assets/3045767/14031886/6410d130-f20f-11e5-87ee-b6f90acf53d1.png)


```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition template="/applayout/pageTemplate.xhtml" xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <ui:define name="content">
        <style>td {padding: 8px;}</style>
        <h1>InputText</h1>
        
        <h:form>
          <b:inputText placeholder="Type something here..." value="#{barcodeBean.emptyText}" required="true" />
          <b:commandButton value="submit and validate" />
          <b:messages />
        </h:form>
        <br/><br/><br/><br/>
    </ui:define>
</ui:composition>
```

**Comment by stephanrauh** [comment] 2016-03-24 21:35
Copying the icons.css to each theme seems to help. However, we'd have to add an extra "../" to the folder names. That's possible, but is there a better way to solve the problem? 

After our talk at the JavaLand conference, I talked to a guy who told me someone reported the solution to this kind to problems - somewhere, in one of our issues. Too bad I forget his name. As far as I remember, he suggested we use something similar to CSS variables or EL expression in our CSS files. @TheCoder4eu Does this ring a bell?

**Comment by zhedar** [comment] 2016-03-24 21:37
@stephanrauh I read https://github.com/TheCoder4eu/BootsFaces-OSP/issues/309 yesterday. Maybe that's what you meant?

**Comment by stephanrauh** [comment] 2016-03-24 21:40
@zhedar Yes, that's almost certainly what I was looking for! Thanks a bundle!

@TheCoder4eu Riccardo, does the hint of Ryan Bennet and Philip Gruhn help us?

**Comment by stephanrauh** [comment] 2016-03-28 14:25
Found the bug concerning the icons.css.

**Comment by zhedar** [comment] 2016-04-01 18:58
I forgot to mention that I got those 404 errors I mentioned again after you fixed that. However I couldn't reproduce it yet, since 0.8.2 broke for me somehow.

**Comment by zhedar** [comment] 2016-04-13 00:55
I tried to narrow the problem down and found, that it was the `CombinedResourceHandler` again, which caused these files to not be found:

    http://localhost:8080/fonts/glyphicons-halflings-regular.woff
    http://localhost:8080/fonts/glyphicons-halflings-regular.ttf
    http://localhost:8080/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
However, I'm not sure, where exactly this originated, it's just that it's lacking the requestContext and probably the resource path, so that's why it's not found.
Now it's also clear, why we weren't experiencing this problem at BootsFacesWeb (the ResourceHandler is disabled there).

Disabling the `CombinedResourceHandler` is no big problem though, but it's somewhat annoying to see these errors again.

Sadly the suggested solution from #309 probably won't be an option, because we can't get the less files to actually close the resource map ending, e.g. `#resource{'filename.eot` would be missing the closing quotes and brackets :(

**Comment by zhedar** [comment] 2016-04-16 20:11
Well, somehow I can't reproduce the 404s anymore. Maybe it was fixed by one of the changes in the last days or it was my build, that was producing those... however I'm happy with that now :)

**Comment by stephanrauh** [comment] 2016-04-19 21:20
@zhedar Is this bug still open?

**Comment by zhedar** [comment] 2016-04-19 21:28
I have currently disabled the `CombinedResourceHandler`, so I did not run into this again. However the last thing may be a totally different issue than this one, so if I run into it again, I may open another ticket. It's not as breaking as this one, because there is no server side error.

**Comment by stephanrauh** [comment] 2016-04-19 21:56
I'll close this ticket because I suspect the issue has been solved, and the youngest messages have little to do with the original error message. Feel free to open a new ticket if you run into problems again.

**Closed by stephanrauh** 2016-04-19 21:56 UTC
Labels: bug, confirmed

**Comment by zhedar** [comment] 2016-05-01 01:47
It seems like https://github.com/TheCoder4eu/BootsFaces-OSP/commit/0810307c80a5c4757012962aaaea186152dab2a7 fixed the remaining problems I had by fixing the actual issue. I could also use the `CombinedResourceHandler` again, all errors vanished in my quick tests.

I guess those 404 errors were triggered by the additional icons.css file in css/theme, because that one wasn't marked as ignored by the ResourceHandler in the web.xml.
