### ISSUE TITLE
Avoid: showing calendar / suggesting current date in <b:dateTimePicker>

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#590] opened 2016-12-18 15:00 UTC
When the `<b:dateTimePicker>` gets focus, the calendar is automatically shown, and if the input is still blank it suggests the current date.

Is it possible to implement a way to avoid both behaviors or one of these individually?

I'd like to show the calendar only when the user click on the calendar icon (which also is not doing), and also not to suggest the current date every time I pass on it.

Thanks in advance.

**Comment by ruanfelisky** [comment] 2016-12-18 15:02
Maybe the fact of not showing the calendar automatically, already solves the "problem" of suggesting the date.

**Comment by stephanrauh** [comment] 2016-12-30 18:42
@ruanfelisky Have a look at http://www3.bootsfaces.net/Showcase/forms/DateTimePicker.jsf. You can use the option `allow-input-toggle` to determine whether the calendar is opened when getting the focus or not.

**Comment by stephanrauh** [comment] 2016-12-30 18:45
The other problem should be solved by setting `use-current="false"`.

**Comment by stephanrauh** [comment] 2016-12-30 18:53
Actually, now it does. We've confused the default value of use-current, so it had no effect. Now it has.

**Comment by stephanrauh** [comment] 2016-12-30 18:54
You can run a test using the BootsFaces-1.1.0-SNAPSHOT on Maven Central. See #369 on how to get it.

**Comment by ruanfelisky** [comment] 2017-01-04 16:56
@stephanrauh I've tested and there is no difference in changing the option `allow-input-toggle`. Using `false` or true `the` calendar is shown when getting focus (using BootsFaces-1.1.0-SNAPSHOT).

About the option `use-current` is working fine.

**Comment by mtvweb** [comment] 2017-01-04 22:14
The error in the PR regarding DataTimePicker are only related to the assigned JQuery id. Sometimes it was correct, sometimes not. 

I've added a fix to my fork. It was confusing about the used id's.Depending on the properties it differs with the assigned form:id and DTP_CONTAINER_ID prefixes.

Hopefully now all cases are working.

**Comment by ruanfelisky** [comment] 2017-01-05 15:52
Hi guys, the current 1.1.0-SNAPSHOT has that last correction?
As soon as it's available, I'll test it on my project.
Thanks.

**Comment by stephanrauh** [comment] 2017-01-05 16:06
I've just uploaded the file. Happy testing!

**Comment by ruanfelisky** [comment] 2017-01-05 16:50
There's only one problem, when I click over the icon, the calendar is not showing. It's strange right? Because in the showcase it's working properly. My code is:
```xml
<b:dateTimePicker allowInputToggle="false" useCurrent="false" label="Data" 
   value="#{myBean.date}" format="DD/MM/YYYY" fieldSize="sm" />
```

**Comment by mtvweb** [comment] 2017-01-05 17:09
Find a snapshot build of my mtvweb-fork at:

https://www.dropbox.com/s/pyx200ngh7shgjc/BootsFaces-OSP-1.1.0-20170105.jar?dl=0
https://www.dropbox.com/s/otojqa1xkma55og/BootsFaces-OSP-default-1.1.0-20170105.jar?dl=0

feel free to check if this is working well with your project

**Comment by stephanrauh** [comment] 2017-01-05 22:02
@mtvweb Yes, this stuff is confusing :). I hope we manage to solve the id issues soon. In the case of the dateTimePicker, it's important to call `$(id).dateTimePicker()` with the outer ID. If the inline mode is active, there's not input field at all, and if there's a calendar icon right or left to the input field, we want it to be part of the datePicker, too. Otherwise clicking the icon doesn't do anything.

**Comment by stephanrauh** [comment] 2017-01-05 22:08
@ruanfelisky I copied your snipped into the showcase, and it works just fine. Clicking the icon shows the calendar. Really strange. Maybe you've got an old snapshot - be it because my upload didn't work, or be it because of a nasty caching problem?

**Comment by mtvweb** [comment] 2017-01-05 22:13
@stephanrauh You're right. I was stumbled by the different cases for the previous change. Have you tried my yesterdays change? I think it is correct now, but I haven't added a PR before I am not sure that it is working in all cases.

I have checked it with the Bootsfaces Showcase with my build and in my project. In any case it is working for me now. The current Showcase doesn't work completely. Check the datetimepicker in the section  "Embedding a DateTimePicker in a form"

https://github.com/mtvweb/BootsFaces-OSP/commit/f5ee461159073dea4805e91232a6959265cac440

**Comment by mtvweb** [comment] 2017-01-06 10:18
I've discovered a funny thing with the "inline" mode.

It is working well for me with Java 8 but not with Java 7. But I can't locate any Java 8 specific code in the DateTimePicker source.

See http://cubie1.ddns.net/BootsFacesWeb/forms/DateTimePicker.jsf for a working example.
(Sorry it is a little bit slow, because it is running only on an ArmV7 Cubietruck with Apache/TomEE-Plume/Java8)

If I run it with Java7, inline behavior is like https://showcase.bootsfaces.net/forms/DateTimePicker.jsf. Toggle inline mode results in an empty rendering.

**Comment by stephanrauh** [comment] 2017-01-07 13:29
@mtvweb @TheCoder4eu Do we have a showcase running on Java 7? I don't have Java 7 on my PC, so I can't test the bug.

**Comment by mtvweb** [comment] 2017-01-07 16:04
I have setup another instance for Java7.

For Java 1.8.0_111 use: 

http://cubie1.ddns.net/BootsFacesWeb/forms/DateTimePicker.jsf

and for Java 1.7.0_51

http://cubie1.ddns.net/BootsFacesWeb7/forms/DateTimePicker.jsf

**Comment by ruanfelisky** [comment] 2017-01-07 16:48
It seems that running in Java 7 really has some bugs in `<b:dateTimePicker>`.

I'm using Java 1.8.0_111 in my project. I will download the BootsFaces-1.1.0-SNAPSHOT again and test to see if the problem regarding the icon has been resolved.

**Comment by stephanrauh** [comment] 2017-01-07 20:42
I can reproduce the bug with your new URL. But are you sure it's a Java bug? The real source of the problem seems to be that moment.js is loaded after the dateTimePicker.min.js, but the latter requires the former:

![image](https://cloud.githubusercontent.com/assets/3045767/21745022/18ed7e78-d522-11e6-83fa-aac08e23e9be.png)

**Comment by stephanrauh** [comment] 2017-01-07 20:51
It's possible that the sort algorithm has been changed between Java 7 and Java 8.

**Comment by stephanrauh** [comment] 2017-01-07 21:08
Hallo Riccardo,

hm, was machen wir mit diesem Fehler? Zwischen Java 7 und Java 8 hat sich - vermutlich - die Implementation der Hashtable geändert. Das Ergebnis ist, dass der DateTimePicker bei Java 8 funktioniert, bei Java 7 nicht.

Wir könnten den AddResourceListener ändern. Aber sollten wir das noch vor der Version 1.0.2 machen? Diese Klasse ist so zentral, Änderungen sind immer sehr gefährlich...

Ich schicke Dir meine beiden Änderungen, dann kannst Du Dir selber ein Bild davon machen. Eigentlich ist es nur eine kleine Änderung. Eigentlich... :)



A tout a l´heur
Stephan

**Comment by stephanrauh** [comment] 2017-01-07 21:38
I've prepared a bugfix, but I'm not sure we'll include it in the 1.0.2 version we'd like to publish this weekend. My bugfix involves the `AddResourcesHandler`, and that's a very central class that has caused us a lot of trouble. We've learned to modify it carefully.

**Comment by mtvweb** [comment] 2017-01-08 10:48
I've compiled the current version from this repository, "inline" is working now, even in Java 7.

But there is still the Id-Issue in it.

I've added a PR https://github.com/TheCoder4eu/BootsFaces-OSP/pull/610 for this, because it is fixed in my repository. My current showcases are now:

* Java 1.8.0_111 with my DateTimePicker Patch from the above PR:
   http://cubie1.ddns.net/BootsFacesWeb/forms/DateTimePicker.jsf

* Java 1.7.0_51 without Patch (clone from TheCoder4eu/BootsFaces-OSP)
   http://cubie1.ddns.net/BootsFacesWeb7/forms/DateTimePicker.jsf

<img width="1178" alt="icon issue" src="https://cloud.githubusercontent.com/assets/2180107/21749141/47ee26c0-d598-11e6-88d8-fa5d0a0761c9.png">

**Closed** 2017-01-09 22:24 UTC
Labels: bug, confirmed

**Comment by stephanrauh** [comment] 2017-01-09 22:47
This should be fixed by now. See http://www3.bootsfaces.net/Showcase/forms/DateTimePicker.jsf. I've uploaded a new snapshot of 1.1.0 so you can test it yourself.

BTW, thanks for being so tenacious! I always looked in the wrong spots, so I didn't see the error. Too bad the bug made it into the 1.0.2 version. The main purpose of this version was to fix the dateTimePicker, along with the colorPicker and one or two other components. Sigh!
