### ISSUE TITLE
JSF Converters

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#319] opened 2016-03-05 19:57 UTC
Hello All,

Can you check the converter operation? At now I try to use a converter for display number with my locale format. I cannot use <f:convertnumer /> because it's cannot display error message(#280) if the number incorrect. Therefore I made a custom converter, but when I submit the form the converter getAsObject method cannot called and I have got the ClassCastException.

I use MyFaces 2.2.9, the response message is:
```xml
<partial-response>
<error>
<error-name>javax.faces.component.UpdateModelException</error-name>
<error-message>org.apache.myfaces.view.facelets.el.ContextAwareELException: javax.el.ELException: Cannot convert 3 000 of type class java.lang.String to class java.lang.Float</error-message>
</error>
</partial-response>
```

Thank you,
Mihaly

**Comment by asterd** [comment] 2016-05-02 07:11
Hi @lyahim,
have you re-check if this issue is still present in bootsfaces 0.8.2 snapshot? 
Maybe, this problem was already solved with another bug fix, because i've try to reproduce your error with myfaces, native or custom converter, and i haven't found errors.. 

Can you please do this check?
Thank you!

@stephanrauh: maybe this error was solved with the edit to getValue2Render of CoreRenderer don't you think?

**Comment by stephanrauh** [comment] 2016-05-02 18:50
It doesn't seem to be solved. At least I managed to reproduce #280. I don't know about custom converters, but I've decided to start with the standard converters first.

**Comment by asterd** [comment] 2016-05-02 19:15
umh.. maybe i've missed something, because i've used custom converter but also f:convertNumber without any problem. The only difference is that i use mojarra...

**Comment by stephanrauh** [comment] 2016-05-02 20:22
Have a look over here: http://www3.bootsfaces.net/Showcase/forms/converters.jsf

Depending on your locale, the number are shown with a decimal comma (in place of the Anglo-Saxon decimal point). If you click on "calculate", the decimal fraction of the numbers gets lost.

**Comment by zhedar** [comment] 2016-05-02 20:28
What would you expect other than that? The converter is set to integer only, it will convert the string given into a integer format, so truncating the decimal places. I guess what's missing is a validator in this case?

**Comment by stephanrauh** [comment] 2016-05-02 20:58
@asterd Your change of the `CoreRenderer` affected the rendering. The problem of #280 (and probably this ticket, too) occurs during the decoding phase.

**Comment by stephanrauh** [comment] 2016-05-02 21:19
@zhedar Good point. Somehow I've missed the integer bit. However, after removing the `integer='true'` attribute, the actionListener isn't called at all. Just in case you're curious: I've pushed the modified version to the showcase.

**Comment by zhedar** [comment] 2016-05-02 21:53
@stephanrauh Well, to be fair I didn't get to run the example again, even with `integerOnly="true"` the listenter isn't called. Was it actually in the showcase?

I feel kind dumb to say this, but I think we're probably doing something wrong. If you replace the bootsfaces input fields by standard `h:inputText`, it will yield the exact same result... so it doesn't seem to work that way.
However, using rich component suites like PrimeFaces never stopped me before, because there's always a another component that does the job (e.g. `InputNumber`). So I actually have to look up, how to use converters now.

**Comment by zhedar** [comment] 2016-05-02 22:01
OMG. Why didn't I see that: `actionLister` <--

**Comment by stephanrauh** [comment] 2016-05-03 18:08
Oops... I know I was tired yesterday, but I wasn't aware my Eclipse was tired, too...

**Comment by stephanrauh** [comment] 2016-05-03 18:12
I'd like to add some documentation and several example of both custom and standard converter. Plus, I'd like to check if `<b:selectOneMenu />` now copes with custom converters. But I'm positive we can close this bug soon.

**Comment by zhedar** [comment] 2016-05-03 19:09
Having several converter examples will let us test this quickly in the future and provides further documentation, so that sounds great. I normally use Omnifaces' [SelectItemsConverter](http://showcase.omnifaces.org/converters/SelectItemsConverter) with `selectOneMenu`s, so maybe we could just check if that one works.

**Comment by stephanrauh** [comment] 2016-05-07 11:25
Let's open a follow-up ticket to document the converters more thoroughly.

**Closed by stephanrauh** 2016-05-07 11:25 UTC
Labels: bug
