### ISSUE TITLE
How to prevent the dropdown from closing by clicking outside?

### ISSUE THREAD

**Issue by atsoares** [TheCoder4eu/BootsFaces-OSP#849] opened 2017-08-25 14:41 UTC
Hi, just to explain my question in Bootstrap we have something like 'hide.bs.dropdown' to do it.
I tried as the same way that it used to be done in bootstrap but it doesn't work.  

Can someone help me?

**Comment by stephanrauh** [comment] 2017-08-26 16:59
Do you refer to this solution?

```javascript
$('.dropdown.keep-open').on({
    "shown.bs.dropdown": function() { this.closable = false; },
    "click":             function() { this.closable = true; },
    "hide.bs.dropdown":  function() { return this.closable; }
});
```

**Comment by atsoares** [comment] 2017-08-28 12:14
Yeah, but it doesn't work 😞

**Comment by atsoares** [comment] 2017-08-28 14:01
Actually, the problem isn't clicking outside. It works now.

But once that I click inside in a wrong place, it closes the dropdown and the solution that you showed stops to work.

**Comment by stephanrauh** [comment] 2017-08-28 17:27
When I tried, I couldn't stop the dropdown from closing when I click outside. Did you manage to do that? If so, would you mind to share your solution with us?

As for clicking inside: How can you click wrong? Or do you refer to selecting the wrong item and not being able to correct your selection because the options panel is already hidden?

**Comment by atsoares** [comment] 2017-08-28 19:57
Sure, just get the right selector that it works:
```javascript
$('.dropdown').on({
    "shown.bs.dropdown": function() { this.closable = false; },
    "click":             function() { this.closable = true; },
    "hide.bs.dropdown":  function() { return this.closable; }
});
```
For example, inside the drowdown I have 5 radio buttons as option. Selecting any option by clicking over it works as usually, but if I click near the radio but inside the panel it will close.  

You can try it by clicking over the 
`<b:navLink></b:navLink>`
in the showcase.

To stop this I've found this solution:
```javascript
$('.dropdown').on('click', function(event){
	    var events = $._data(document, 'events') || {};
	    events = events.click || [];
	    for(var i = 0; i < events.length; i++) {
	        if(events[i].selector) {
	            if($(event.target).is(events[i].selector)) {
	                events[i].handler.call(event.target, event);
	            }
	            $(event.target).parents(events[i].selector).each(function(){
	                events[i].handler.call(this, event);
	            });
	        }
	    }
	    event.stopPropagation(); 
});
```

**Comment by stephanrauh** [comment] 2017-08-28 20:18
Thanks! I think we might add the five-lines JavaScript code as an option. The advanced solution is probably an advanced use case that doesn't apply to everybody. So I'd prefer to mention it in the showcase.

How do you like this idea?

**Comment by atsoares** [comment] 2017-08-28 20:47
That'ts true. But the five-lines Javascript doesn't work totally. Once that you click inside if you click outside, it will close the panel. Didn't figured out how to stop it, but at least the wrong click problem is solved on my phone. 

I liked the idea, as an option is the best way to do it.

**Comment by stephanrauh** [comment] 2017-08-29 21:40
Oh. We're talking about different components. I thought about `<b:selectOneMenu>`. But this component doesn't support any `*.bs.*` event. Which component are you referring to? Can you show us a little reproducer?

**Comment by atsoares** [comment] 2017-08-30 11:30
Oh sorry. the question is about the ```<b:dropMenu>```. I'm using it like a filter 

```
<b:dropMenu id="dropMenu" display="visible" icon-awesome="filter" value="" rendered="#{seguranca.usuarioLogadoTO.filiais.size() gt 1}" tooltip="Filtrar repasse" tooltip-position="left" tooltip-delay-show="300" tooltip-delay-hide="300">

  <b:listLinks>
    <b:navLink header="Filiais" />
    <h:selectManyCheckbox style="margin-left: 10px" value="#{repasseEstabelecimentoULBean.filtro.idFilialEstabelecimentoSelecionado}" layout="pageDirection">
      <f:selectItems value="#{seguranca.usuarioLogadoTO.filiais}" var="aux" itemValue="#{aux.idFilialEstabelecimento}" itemLabel="#{aux.txNomeReduzidoNrSeguranca}" />
    </h:selectManyCheckbox>
  </b:listLinks>

  <b:listLinks>
    <b:navLink header="Período" />
    <b:row>
      <b:column>
        <b:inputText autocomplete="off" required="true" styleClass="date" type="tel" label="De" value="#{repasseEstabelecimentoULBean.filtro.dtGeracaoInicial}" converter="dataConverter" validator="dataValidator">
        </b:inputText>
      </b:column>
    </b:row>
    
    <b:row>
      <b:column>
        <b:inputText autocomplete="off" required="true" styleClass="date" type="tel" label="Até" value="#{repasseEstabelecimentoULBean.filtro.dtGeracaoFinal}" converter="dataConverter" validator="dataValidator">
        </b:inputText>
      </b:column>
    </b:row>

    <b:row>
      <b:column style="margin-top: 5px; text-align:center">
        <b:commandButton value="Atualizar" ajax="false" action="#{repasseEstabelecimentoULBean.pesquisar}" onclick="$('.wait').show();" look="primary"></b:commandButton>
      </b:column>
    </b:row>
  </b:listLinks>
![sem titulo](https://user-images.githubusercontent.com/17599235/29870352-6a57cffe-8d5d-11e7-9773-10b25ac354d6.png)

</b:dropMenu>
```

**Closed** 2019-04-15 13:34 UTC
Labels: enhancement, verifying issue
