### ISSUE TITLE
<b:modal>  not working properly on mobile

### ISSUE THREAD

**Issue by nickolaz** [TheCoder4eu/BootsFaces-OSP#966] opened 2018-07-10 14:30 UTC
Hi, i am using bootsfaces on my project. the issue i am facing is that the modal is not being displayed as per required on mobile screen. the modal is fixed the the top of the page with fade screen. it doesn't close and don't scroll

Can somebody help me please that how i can fix this issue.
![pc](https://user-images.githubusercontent.com/18169294/42516601-2fab3514-842c-11e8-92ba-1bf02cca93f4.png)
![mobile](https://user-images.githubusercontent.com/18169294/42516600-2f79be80-842c-11e8-8ac1-eaf991310491.png)

**Comment by chongma** [comment] 2018-07-10 14:40
you might need to provide a working sample application which shows the problem.  i don't really use modals much in my projects.  you could create a working TomEE app as a starting point by running mvn archetype:generate -DarchetypeGroupId=org.apache.tomee.maven -DarchetypeArtifactId=tomee-webapp-archetype -DarchetypeVersion=7.0.3

@stephanrauh if i created a working archetype which included BootsFaces already integrated how do we get it uploaded to maven central?

**Comment by stephanrauh** [comment] 2018-07-10 18:39
It's interesting that we didn't document closing a modal. We've documented it implicitly, so most people manage to understand what we haven't written down yet, but there's headroom to improve :).

BTT: What did you do to hide the modal? Basicially, there are four different options:

- The "close cross" https://showcase.bootsfaces.net/bootstrap/modal.jsf#closable
- backdrop="true"
- `<b:button value="Close" dismiss="modal" />`
- $('.modalPseudoClass').modal('hide');

**Comment by stephanrauh** [comment] 2018-07-10 18:45
@chongma According to stackoverflow, it's very simple: https://stackoverflow.com/questions/23160461/how-i-add-my-archtype-to-the-maven-central-archetype-catalog-xml

I can upload the archetype under the net.bootsfaces namespace. Do you think that's enough? Or do we need to do more in advance?

**Comment by chongma** [comment] 2018-07-11 07:13
@stephanrauh i think the problem is that the modal is greyed out so it is not possible to click it at all on mobile

**Comment by stephanrauh** [comment] 2018-07-16 17:09
We can't solve a but we can't reproduce. For the moment, I'll close the ticket. We'll happily re-open it when you send us a reproducer.

**Closed by stephanrauh** 2018-07-16 17:09 UTC
Labels: User support
