### ISSUE TITLE
OmniFaces CombinedResourceHandler problem with Glyphicons

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#688] opened 2017-04-08 14:44 UTC
Glyphicons don't work when that ResourceHandler. The documentation has it disabled but enabling it reveals the problem.

Happens with OmniFaces 2.6.1 but also with the patched 1.12 version the web uses.

**Comment by stephanrauh** [comment] 2017-04-15 13:23
The problem is that the regular CSS files are in a subfolder. The combined CSS file of OmniFaces is one folder up. So the relative paths pointing to the Glyphicons font points to the wrong direction after being combined by OmniFaces.

**Comment by stephanrauh** [comment] 2017-04-15 13:30
I've opened a bug report on the OmniFaces repository: https://github.com/omnifaces/omnifaces/issues/371.

**Comment by ggam** [comment] 2017-04-15 14:54
I'm not that sure this is an OmniFaces problem at all.

Our CSS use be using #{resource['boostfaces/xxx.tif']} references so that
JSF can replace it to whatever the final location is.

We should first check if that solves the problem.

**Comment by stephanrauh** [comment] 2017-04-15 15:23
Have a look at the `bs-core.css` files:

```css
@font-face {
	font-family: 'Glyphicons Halflings';
	src: url('../../../fonts/glyphicons-halflings-regular.eot');
	src: url('../../../fonts/glyphicons-halflings-regular.eot?#iefix')
		format('embedded-opentype'),
		url('../../../fonts/glyphicons-halflings-regular.woff2')
		format('woff2'),
		url('../../../fonts/glyphicons-halflings-regular.woff') format('woff'),
		url('../../../fonts/glyphicons-halflings-regular.ttf')
		format('truetype'),
		url('../../../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular')
		format('svg');
}
```

**Comment by ggam** [comment] 2017-04-15 17:36
I was referring to http://stackoverflow.com/questions/8367421/how-to-reference-css-js-image-resource-in-facelets-template (Referencing in EL, from Bauke's reply).

That way allows JSF to generate the paths and maybe automatically fix this. Or are there any reasons not to use that method?

**Comment by stephanrauh** [comment] 2017-04-15 17:42
Of course, you're right: that's the way to go. Unfortunately, the link to the Glyphicons is part of the standard Bootstrap CSS files. We're reluctant to modify them during the Gradle build. Mind you, each time the Gradle build runs, the source files of Bootstrap are downloaded, compiled by the LESS compiler and so on. So it's not enough to modify the CSS file. Instead, we have to write a Gradle script that modifies the CSS file.

**Comment by ggam** [comment] 2017-04-15 17:49
Thanks for the explanation!

Overriding that CSS classes from a BootsFaces file could do the trick for
now?

**Comment by stephanrauh** [comment] 2017-04-15 18:00
Yes, now that you say it: sure, that's an option. Sounds like a simple one, too.

**Comment by ggam** [comment] 2017-04-15 18:49
At least for 1.1.0 it'd allow to maintain compatibility with OmniFaces.
It's not very smart, but will work for now.

**Comment by stephanrauh** [comment] 2017-04-30 19:48
It seems we've forgotten to close this ticket.

**Closed by stephanrauh** 2017-04-30 19:48 UTC
