### ISSUE TITLE
Integration with ButterFaces ERROR!

### ISSUE THREAD

**Issue by cooper-lyt** [TheCoder4eu/BootsFaces-OSP#414] opened 2016-06-15 17:18 UTC
Integration butterFaces 2.1.4 , all DropDown menu is invalid！

maven:
`<dependency>
      <groupId>de.larmic.butterfaces</groupId>
      <artifactId>components</artifactId>
      <version>2.1.4</version>
    </dependency>`

web.xml
`<context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Production</param-value>
  </context-param>`

but, if set `javax.faces.PROJECT_STAGE` to `Development` will be ok! 
i view the html source , if set `javax.faces.PROJECT_STAGE` to `Production`  then add include a script:
`<script type="text/javascript" src="/RestaurantERP_SNAPSHOT/javax.faces.resource/butterfaces-all-with-jquery-and-bootstrap-bundle.min.js.xhtml?ln=butterfaces-dist-bundle-js">`

**Comment by zhedar** [comment] 2016-06-15 23:54
You are right, I could reproduce this in the Showcase. However, as far as I know, ButterFaces integration was problematic for a long time, we currently have version `1.10.3` in the Showcase, which doesn't have this bug. So I guess it's actually out of scope of BootsFaces. Maybe this should be reported to ButterFaces as well.

**Comment by larmic** [comment] 2016-06-17 08:34
Is web.xml param net.bootsfaces.get_jquery_from_cdn in 0.8.6  no longer supported? I found 

```<script type="text/javascript" src="/javax.faces.resource/jq/jquery.js.jsf;jsessionid=ZNijnq-jtzLlD735AQghln9K1mWE8ODVAbd8ltM8.larmic-mbpr?ln=bsf"></script>```

in our ButterFaces/BootsFaces demo when using newest version of BootsFaces

**Comment by zhedar** [comment] 2016-06-17 15:30
We didn't change that. I refactored it with 0.8.5 though, maybe I broke it. Probably will test its functionality tonight.

**Comment by zhedar** [comment] 2016-06-19 23:24
@larmic I finally got to check this and setting `net.bootsfaces.get_jquery_from_cdn` to `true` atleast shouldn't include our version of jQuery. However, it also doesn't load it via CDN it seems, I'm not sure if we removed that feature on accident.

**Comment by larmic** [comment] 2016-06-21 08:56
Are you have a parameter to use my own jQuery instead of getting it from BootsFaces?

**Comment by zhedar** [comment] 2016-06-21 09:54
@larmic That's, what I'm describing in #421. The parameter name is a bit misleading.
You have to set `net.bootsfaces.get_jquery_from_cdn` to `true` to use your own version of jQuery.

Taken from the [Showcase](http://showcase.bootsfaces.net/layout/resourcemanagement.jsf):
> Setting the context parameter net.bootsfaces.get_jquery_from_cdn to "yes" or "true" allows you to provide your own jQuery file.

As you've stumbled upon that one too, we should probably do something about it ;)

**Comment by larmic** [comment] 2016-06-21 10:05
Ok, may this has been changed? In further versions of BootsFaces it works the other way around.

When switching to true it most features works. Dropdown is still not working and no JS error occurs.

See https://github.com/ButterFaces/bootsfaces-integration

**Comment by zhedar** [comment] 2016-06-21 11:37
This part shouldn't have changed since it was introduced, atleast the documentation seems to haven't changed since. (At least git blame says that, maybe it was moved.) Which versions did you mean?

Maybe you can try different versions of butterfaces (or even commits) and trace the breaking change down that way. Like I wrote before, it was working with `1.10.3`, which is present in our Showcase.

**Comment by larmic** [comment] 2016-06-22 10:47
With BootsFaces 0.8.1 I could set net.bootsfaces.get_jquery_from_cdn to true and false with same effect. Maybe it was broken in this version.

It is correct that you provide a bootstrap dropdown.js even if I set net.bootsfaces.get_bootstrap_from_cdn?

**Comment by zhedar** [comment] 2016-06-22 11:12
The behaviour in 0.8.1 looks a bit suspicious, 

@larmic Looking at the source code, we only remove the CSS files in the `bsf` library, when that option is selected. Therefore, this won't remove any JavaScript files. Maybe we should exclude them as well. 
Problem with that is only, that we may have to restructure our directories and it will leave the application pretty unfunctional otherwise (as we include some files, which aren't coming from Bootstrap).

**Comment by larmic** [comment] 2016-06-22 11:58
@zhedar 
In ButterFaces you can set org.butterfaces.provideBootstrap to false which means no Bootstrap will be provided by ButterFaces. In this case the user must add Bootstrap by himself in correct order.

**Comment by stephanrauh** [comment] 2018-07-23 18:44
I suggest we close the issue. It lay dormant for a long time, and I suppose we've already fixed the bug (if there was any).

**Closed by stephanrauh** 2018-07-23 18:44 UTC
Labels: issue with other JSF fwk
