### ISSUE TITLE
b:commandButton onclick executed twice?

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#826] opened 2017-07-23 15:06 UTC
If I click the button described below it prompts me twice to confirm.  Is the code being executed twice?
```
<b:commandButton value="Delete" iconAwesome="trash"
    action="#{testBean.delete}"
    onclick="if (! confirm('Are you sure?')) return false">
    <f:setPropertyActionListener target="#{testBean.id}"
        value="#{testItem.id}" />
    <f:ajax execute="@this" render="@form" />
</b:commandButton>
```
Bear in mind the code was inside a b:dataTable

**Comment by stephanrauh** [comment] 2017-07-25 20:28
It seems the onclick handler is rendered twice:
```xml
                 	<b:commandButton value="Delete" iconAwesome="trash"
					    action="#{car.edit}"
					    onclick="debugger">
					    <f:ajax execute="@this" render="@form" />
					</b:commandButton>
```
```html
<button type="submit" id="j_idt351:j_idt352:14:j_idt363"
	name="j_idt351:j_idt352:14:j_idt363" class="btn btn-default"
	onclick="debugger;debugger;BsF.ajax.callAjax(this, event,'j_idt351','j_idt351:j_idt352:14:j_idt363',null,null,null,null);;;return false;">
	<span><i class="fa fa-trash"></i></span> Delete
</button>
```

**Comment by stephanrauh** [comment] 2017-07-25 20:31
The reproducer can be simplified to
```xml
<h:body>
  <h:form>           
    	<b:commandButton value="Delete" iconAwesome="trash"
	    onclick="debugger">
	    <f:ajax execute="@this" render="@form" />
	</b:commandButton>
  </h:form>
</h:body>
```

**Comment by stephanrauh** [comment] 2017-07-25 20:32
I guess the problem is that `<b:commandButton>` renders the `onclick` attribute, and `f:ajax` renders it again.

**Comment by stephanrauh** [comment] 2017-07-25 21:03
@chongma Maybe you want to review my last change. It should do the trick, but it's kind of a hack. If you've got a better solution, just tell me (or commit it yourself :)).

**Comment by chongma** [comment] 2017-07-26 10:11
looks good to me

**Comment by stephanrauh** [comment] 2017-07-26 20:58
I still can't think of a better solution, so I'll close this ticket. @chongma , thanks for testing!

**Closed by stephanrauh** 2017-07-26 20:58 UTC
Labels: bug, confirmed
