### ISSUE TITLE
<b:selectOneMenu> validation: "bf-error" CSS pseudo class not applied on error

### ISSUE THREAD

**Issue by mistahboz** [TheCoder4eu/BootsFaces-OSP#449] opened 2016-07-05 09:26 UTC
When using validation (such as `required="true"`) on `<b:selectOneMenu>` the CSS pseudo class "bf-error" is not applied to the `select` tag on validation fail.

**Comment by stephanrauh** [comment] 2016-12-22 22:35
Please have a look at #593 and http://www3.bootsfaces.net/Showcase/forms/selectOneMenu.jsf#errorClasses. I believe this is a duplicate of this error, so we'll track progress in #593. If I'm wrong, just answer in this issue: We're still listening to it. 

Thanks for your understanding (and your patience - for some reason, this issue slipped my attention!)
Stephan

**Closed by stephanrauh** 2016-12-22 22:35 UTC
Labels: bug, verifying issue

**Comment by stephanrauh** [comment] 2016-12-26 20:20
I've just closed #593. I assume this bug is solved now, too.
