### ISSUE TITLE
DataTables in v. 1.4.2 are not with bootstrap theme

### ISSUE THREAD

**Issue by vsvetoslavov** [TheCoder4eu/BootsFaces-OSP#1104] opened 2019-11-12 08:53 UTC
In BootsFaces version 1.4.2 the DataTable does not use the bootstrap theme from datatables.net. Is there any reason for that? Seems like a bit of downgrade...

**Comment by stephanrauh** [comment] 2020-05-06 20:41
I just noticed that in the showcase, too. Whatever has happened, it wasn't intended!

**Comment by stephanrauh** [comment] 2020-05-06 21:20
It seem we've fixed the bug some time ago, but it doesn't show in the showcase yet. We're investigating what's wrong. This may take some time.

**Comment by frankyhoffmann** [comment] 2020-05-07 13:22
join.skype.com/ltcvXRujoEed

**Comment by stephanrauh** [comment] 2020-05-10 20:02
We've managed to repair the showcase tonight. There's a minor layout glitch of the datatable, but that's covered by another ticket, so I'll close this ticket now.

**Closed by stephanrauh** 2020-05-10 20:02 UTC
Labels: Solved, confirmed, dataTable

**Comment by stephanrauh** [comment] 2020-05-11 14:28
The display glitch is a false positive. It has been caused by the cache of my browser.
