### ISSUE TITLE
panel component render invalid tag

### ISSUE THREAD

**Issue by lyahim** [TheCoder4eu/BootsFaces-OSP#306] opened 2016-02-23 20:08 UTC
Hello All,

Just a minor bug, there is a needless link close tag in panel header.
```xml
<div class="panel-heading"><h4 class="panel-title">title!!!</a>!!!</h4></div>
```
Best Regards,
Mihaly

**Comment by stephanrauh** [comment] 2016-02-23 21:06
I didn't manage to reproduce the bug. The code

```xml
<b:panel title="title!!!">!!!</b:panel>
```

generates

```xml
    <div class="panel-group">
      <div id="j_id_33" class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-target="#j_id_33content">title!!!</a>
          </h4>
        </div>
        <div id="j_id_33content" class="panel-body  panel-collapse collapse in">!!!</div>
      </div>
    </div>
    <input type="hidden" name="j_id_33_collapsed" id="j_id_33_collapsed" value="false" />
    <script>$('#j_id_33content').on('show.bs.collapse', function(){document.getElementById('j_id_33_collapsed').value='false';});</script>
    <script>$('#j_id_33content').on('hide.bs.collapse', function(){document.getElementById('j_id_33_collapsed').value='true';});</script>
```

Adding `collapsible="false"` make the anchor tag vanish altogether.

**Comment by lyahim** [comment] 2016-02-24 07:46
Before I post the issue, I reviewed the source and cannot find any bug. But in console I get this message:
HTML nesting warning on closing a: element h4 rendered by component : {Component-Path : [Class: javax.faces.component.UIViewRoot,ViewId: /login.xhtml][Class: javax.faces.component.html.HtmlBody,Id: j_id_6][Class: javax.faces.component.html.HtmlForm,Id: j_id_7][Class: net.bootsfaces.layout.Container,Id: j_id_8][Class: net.bootsfaces.layout.Row,Id: j_id_9][Class: net.bootsfaces.component.column.Column,Id: j_id_a][Class: net.bootsfaces.component.panel.Panel,Id: j_id_c]} not explicitly closed

And the generated html is what I posted.

The tag source is 
```xml
<b:panel title="#{msg['login.title']}" collapsible="false">...</b:panel>
```

Some days ago I switch the jsf core implementation from official(javax.faces) to myfaces implementation. This message show only myfaces. Therefore it is possible a myfaces issue.

Mihaly

**Comment by stephanrauh** [comment] 2016-04-30 20:35
@lyahim I've tested the non-collapsible panel with MyFaces 2.2.8. To no avail: I couldn't reproduce the error.

It's a bit unsatisfying to close an issue reported by such a reliable resource as you, Mihaly, but since I don't see any but, I've decided to close the issue. Feel free to reopen it if you've got news.

**Closed by stephanrauh** 2016-04-30 20:35 UTC
Labels: bug, verifying issue
