### ISSUE TITLE
Bootstrap theme in b:dataTable

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#712] opened 2017-04-20 11:16 UTC
It looks like the <b: dataTable> has lost some of the bootstrap theme.
I am using the latest version 1.1.0-SNAPSHOT.

Example:

![image](https://cloud.githubusercontent.com/assets/4307334/25228122/8911a7d6-25a1-11e7-94fd-fabf937b178e.png)

**Comment by NicolaIsotta** [comment] 2017-04-20 14:43
Seems like the problem is caused by this @TheCoder4eu 's [commit](https://github.com/TheCoder4eu/BootsFaces-OSP/commit/f762163534d2f860905e29ce685d92bdf2752975) (open the first diff and look at the url: `#bs` -> `#dt`)

**Comment by ruanfelisky** [comment] 2017-04-20 17:44
Is it possible to solve this in 1.1.0?
Tks.

**Comment by TheCoder4eu** [comment] 2017-04-20 20:38
@NicolaIsotta could be, I was updating datatables but something must have gone wrong with the options selection for the download...

**Comment by TheCoder4eu** [comment] 2017-04-20 20:51
@NicolaIsotta what you pointed out is correct, I am going to update the files with the version with `#bs` in the url (who knows what the exact effect is...) .

However, since in our staging area we do not see the problem, I ask @stephanrauh to update the snapshot.

**Comment by chongma** [comment] 2017-04-21 14:08
confirmed.  i just realised my 1.1.0-snapshot was stuck on an old version.  i cleared my .m2/repository and now it shows the dataTable messed up

**Comment by stephanrauh** [comment] 2017-04-21 17:44
I've just uploaded a new developer snapshot of BootsFaces. The old snapshot was already several days old. Please test again.

**Comment by stephanrauh** [comment] 2017-04-21 17:47
Oh - wait. The bug seems to affect the Maven build only. The Gradle build seems to be OK.

**Comment by stephanrauh** [comment] 2017-04-21 18:07
@NicolaIsotta @chongma 
OK, this time for real. I've uploaded another developer snapshot of BootsFaces. Please clear your Maven cache and your browser cache. The first time I ran the test, the page looked even worse than before because of caching problems.

**Comment by chongma** [comment] 2017-04-21 18:25
i have cleared the cache and can confirm that it is working

**Comment by TheCoder4eu** [comment] 2017-04-21 22:31
@chongma great, thanks!

**Comment by stephanrauh** [comment] 2017-04-22 12:16
I think we can close the issue. Thanks for testing!

**Closed by stephanrauh** 2017-04-22 12:16 UTC
Labels: bug, confirmed
