### ISSUE TITLE
Problem with colorpicker not rendering correctly

### ISSUE THREAD

**Issue by wtf35** [TheCoder4eu/BootsFaces-OSP#634] opened 2017-02-10 10:41 UTC
Hi, 
I'm new to Bootsfaces and I have a problem with the colorpicker in my JSF 2.2 project. I use the last maven dependendy (bootsfaces-1.0.2).

If in my .xhtml file, I add any jquery.js file (tried newest version jquery-3.1.1.js), then the <b:colorpicker/> is displayed as a simple input text box (with no small button to open colors). 
On the other hand, if I don't include any jquery*.js file, the control is displayed correctly. 

I guess Bootsfaces comes with Jquery libraries already included, but I need JQuery for other things in my web page, so I need to include it separately.

Any ideas?

**Comment by stephanrauh** [comment] 2017-02-10 13:05
That's not surprising. BootsFaces already adds jQuery, so you don't need to add it yourself. If you need to add a certain version of jQuery for some reason, http://showcase.bootsfaces.net/layout/resourcemanagement.jsf explains how to do it.

**Comment by stephanrauh** [comment] 2017-02-10 13:05
Please report back if this solves your issue, so we can close the ticket. 

Thanks in advance!
Stephan

**Comment by stephanrauh** [comment] 2017-02-16 21:24
@wtf35 Do you still have the bug, or did you manage to solve it in the meantime so we can close the issue?

**Comment by wtf35** [comment] 2017-02-20 17:12
Not solved. I tried everything. 
I need to load a separate jquery.js because JQ is only available to pages that contain at least bootsfaces tag (<b:xxxxx/>), otherwise JQ it's not present. And I have some xhtml pages without any <b:xxxxx/> tags.
I tried last JQ version 3.1.1 and the 2.2.4, the same contained in bootsfaces 1.0.2, no luck so far.

Also tried it with all the possibilities with the setting in web.xml (tried true and false):

```
<context-param>
        <param-name>net.bootsfaces.get_jquery_from_cdn</param-name>
        <param-value>true</param-value>
    </context-param> 
```

And everytime I load my own jquery file, no colorpicker is rendered well (shown like a normal input box), no matter the value in the param net.bootsfaces.get_jquery_from_cdn.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
   	  xmlns:h="http://xmlns.jcp.org/jsf/html"
   	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
   	  xmlns:b="http://bootsfaces.net/ui">
<h:head>
 	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"/>
 </h:head>
<h:body>
	<b:colorPicker/>
</h:body>
</html>
```

**Comment by stephanrauh** [comment] 2017-02-20 20:51
Did you try
```xml
 <h:outputStylesheet src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js" position="first"/>
```
along with `net.bootsfaces.get_jquery_from_cdn`?

Oh, and please check (and report) the order of the JavaScript imports in the generated HTML file. Probably, this gives you a hint what's going wrong. In most cases, the problem is that libraries like jQuery are loaded and initialized in the wrong order or twice.

**Comment by wtf35** [comment] 2017-02-21 17:50
Man, I guess you mistyped something in:
` <h:outputStylesheet src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js" position="first"/>`
1. AFAIK <h:outputStylesheet is only valid for including LOCAL .css files (not URLs), and not .js files (which Jquery is). Maybe u meant <h:outputScript ? I think neither since it doesn't load URLs, just local files.
2. There's no "src" and "position" attributes in <h:output**** /> tags. Can't find any of those in jsf 2.2 reference.

I guess the only choice is:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js" position="first"/>`
But Eclipse tells me position is an unknown attribute and the colorpicker is having the same problem.

**Comment by stephanrauh** [comment] 2017-02-21 20:27
To my surprise, you are right. Not only did I mistake the tag names, but I also wasn't aware there's no src tag. Let alone that the CDN attribute in the web.xml is broken. 

I suggest we perform these two steps:
- Implement the "src" attribute of `<h:outputScript>` and `<h:outputStylesheet>`, even if it's non-standard.
- Add the position attribute to `<h:outputScript>`.

@TheCoder4eu @zhedar @asterd What's your opinion?

**Comment by stephanrauh** [comment] 2019-08-03 17:53
I've tried to reproduce the problem. Maybe it has gone away during one of the countless optimizations of the `AddResourcesListener`. Be that as it may, adding this line replaced the standard implementation of jQuery by a custom implementation:

```xml
  <h:outputScript library="jq" name="jquery-uncompressed.js" target="head"></h:outputScript>
```

**Closed by stephanrauh** 2019-08-03 17:53 UTC
Labels: bug, confirmed
