### ISSUE TITLE
Bootsfaces integration with Colorbox - a jQuery lightbox

### ISSUE THREAD

**Issue by MelvinAvalos** [TheCoder4eu/BootsFaces-OSP#839] opened 2017-08-16 21:05 UTC
I try to use Colorbox jQuery lightbox inside <b:container> but this does not work. When i delete <b:container> this work correctly. The same problem occurr when i use other component of bootfaces in the page. In the future is possible integrate the compatibility with this library?

[Galeria.zip](https://github.com/TheCoder4eu/BootsFaces-OSP/files/1229529/Galeria.zip)

**Comment by stephanrauh** [comment] 2017-08-19 19:56
Whow, you've included a reproducer project without asking. Thanks!

**Comment by stephanrauh** [comment] 2017-08-19 20:08
Actually, I can't reproduce the bug. To me, the colorbox seems to work fine, no matter whether I put a container around the page or not.

I've noted (and changed) two things:

- I've remove the Richfaces code. We don't support RichFaces officially. As far as I remember, you can use RichFaces along with BootsFaces, but it's not easy.
- I've removed the jQuery import because BootsFaces already imports jQuery. Maybe that's the cause of your bug.

If this doesn't solve your bug, where did you put the `b:container` tag precisely?

**Comment by stephanrauh** [comment] 2017-12-26 19:22
There hasn't been any update on this ticket for a couple of months, so I'll close it now. Especially since I tried to manage to reproduce the bug without problems. Quite the contrary, the colorbox worked flawlessly at the time.

**Closed by stephanrauh** 2017-12-26 19:22 UTC
Labels: bug, verifying issue
