### ISSUE TITLE
New component datetimepicker

### ISSUE THREAD

**Issue by anemdhana** [TheCoder4eu/BootsFaces-OSP#148] opened 2015-08-01 08:21 UTC
Hi,
Could you implement the datetimepciker for the following library and with conversion of joda time formats ?
http://eonasdan.github.io/bootstrap-datetimepicker/
(or)
http://www.daterangepicker.com/

Thanks in advance.

**Comment by stephanrauh** [comment] 2015-08-01 11:04
I prefer the datarangepicker. It's provided under the MIT license, which is compatible to the license of BootsFaces.

**Comment by AlexanderBl4h** [comment] 2015-08-01 11:08
:+1:  for http://www.daterangepicker.com/

**Comment by stephanrauh** [comment] 2015-08-01 11:09
I'm closing this ticket because it's a duplicate of #144. Please follow ticket #144 to watch the progress.

**Closed** 2015-08-01 11:09 UTC
Labels: duplicate, enhancement
