### ISSUE TITLE
Bug text value for CommandButton compenent since bootsfaces 0.7

### ISSUE THREAD

**Issue by atelyak** [TheCoder4eu/BootsFaces-OSP#227] opened 2015-12-31 10:54 UTC
Hello,

i'm facing a problem about the value attribute for the CommandButton attribute since the 0.7 version.

When i type a text into the value atrribute.
The text is empty on the screen.
With older version of bootsface (0.6.6 for example) the value attribute working and showing
 my text into de Button on the screen.

**The results in bootsfaces 0.8.0**

![login](https://cloud.githubusercontent.com/assets/16499584/12063746/28970d38-afb4-11e5-932b-7928e989ee08.png)

**In bootsfaces 0.6.6 with the same code (i have only changed the version in the pom file)**

![login 0_6_6](https://cloud.githubusercontent.com/assets/16499584/12063759/65efa582-afb4-11e5-9cde-fa1152d9a17b.png)

Can you help me ? i have tried : 
 
With omnifaces -> doesn't working.
I have tried to run on Tomcat and Glassfish -> not working.

I don't understand why my project showing good (only with commandbutton the other compenents working good) with only older version of Bootsfaces ?

Thank you.

**__this is part of source code__**

**Login.xhtml :** 
```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui" style=" height: 100%">
    <h:head>
        <title>ListGenerator</title>
        <h:outputStylesheet library="css" name="css1.css" />
    </h:head>
            <f:metadata>
                <f:event listener="#{IdentificationController.init()}" type="preRenderView" />
            </f:metadata>
    <h:body style="background-color:#EEE;" >
        <h:form id="form" style="width:100%; background-color:#EEE;" rendered="#{IdentificationController.session}">
            <p:idleMonitor timeout="3600000" onidle="PF('idleDialog').show()" />
                <p:confirmDialog id="confirmDialog"
                            message="La session a été clôturée. Vous devez recharger la page en sélectionnant l'url et appuyez sur enter"
                            header="Session clôturée" severity="alert" widgetVar="idleDialog">
                </p:confirmDialog>
            <p:growl life="10000" id="growl"/>
            <p:focus />
            <p:panelGrid style="margin: 0 auto; font-size:95%; background-color:#EEE;">
                    <!-- LOGIN -->
                    <p:row>
                        <p:column style="background-color: #EEE !important;" >
                            <h2>Authentification</h2>
                        </p:column>
                    </p:row>
                    <!-- Login -->
                    <p:row>
                        <p:column style=" background-color: #EEE !important;" >
                            <b:inputText id="TxtLogin"
                                       value="#{IdentificationController.login}"
                                       required="true" >
                            <f:facet name="prepend">
                                <b:iconAwesome name="user" />
                            </f:facet>
                            </b:inputText>
                            <p:watermark for="TxtLogin" value="Login" id="watermark" />
                        </p:column >
                    </p:row>
                    <!-- PW -->
                    <p:row>
                        <p:column style="background-color: #EEE !important;" >
                            <b:inputSecret id="TxtPw"
                                         value="#{IdentificationController.password}"
                                         required="true">
                            <f:facet name="prepend">
                                <b:iconAwesome name="key" />
                            </f:facet>
                            </b:inputSecret>
                            <p:watermark for="TxtPw" value="Mot de passe" id="watermark2" />
                        </p:column >
                    </p:row>
                    <!-- BOUTON  -->
                    <p:row>
                        <p:column style="text-align:center; background-color: #EEE !important;">
                            <b:commandButton value="Se connecter" id="BLImg" ajax="false" look="primary"  style="width:100%;"
                               action="#{IdentificationController.identify}"/>
                        </p:column >
                    </p:row>
        </p:panelGrid>
        </h:form>
        <h:form id="form2" style="width:100%;" rendered="#{!IdentificationController.session}">
            <center>
                <p> vous êtes déjà connecté en tant que <span style="color:green">#{IdentificationController.login}</span> veuillez cliquer sur le button plus bas pour être redirigé </p>
            <br />
            <b:commandButton look="primary" ajax="false" action="index.xhtml" value="Redirection vers ListGenerator"/>
            </center>
        </h:form>
    </h:body>
</html>
```
**Pom.xml :** 
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>be.slbo</groupId>
	<artifactId>ListGenerator</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>war</packaging>

	<name>ListGenerator</name>

	<properties>
		<endorsed.dir>${project.build.directory}/endorsed</endorsed.dir>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.eclipse.persistence</groupId>
			<artifactId>eclipselink</artifactId>
			<version>2.5.2</version>
		</dependency>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-web-api</artifactId>
			<version>7.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.primefaces.extensions</groupId>
			<artifactId>all-themes</artifactId>
			<version>1.0.8</version>
		</dependency>

		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>5.3</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.faces</artifactId>
			<version>2.2.7</version>
		</dependency>
		<dependency>
                    <groupId>net.bootsfaces</groupId>
                    <artifactId>bootsfaces</artifactId>
                    <version>0.8.0</version>
                    <scope>compile</scope>
                </dependency>

                <dependency>
                        <groupId>jstl</groupId>
                        <artifactId>jstl</artifactId>
                        <version>1.2</version>
                </dependency>

		<dependency>
			<groupId>commons-logging</groupId>
			<artifactId>commons-logging</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>2.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.9</version>
		</dependency>
		<dependency>
			<groupId>dom4j</groupId>
			<artifactId>dom4j</artifactId>
			<version>1.6.1</version>
		</dependency>

		<dependency>
			<groupId>com.unboundid</groupId>
			<artifactId>unboundid-ldapsdk</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.novell.ldap</groupId>
			<artifactId>jldap</artifactId>
			<version>4.3</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
					<compilerArguments>
						<endorseddirs>${endorsed.dir}</endorseddirs>
					</compilerArguments>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.1.1</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.1</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>copy</goal>
						</goals>
						<configuration>
							<outputDirectory>${endorsed.dir}</outputDirectory>
							<silent>true</silent>
							<artifactItems>
								<artifactItem>
									<groupId>javax</groupId>
									<artifactId>javaee-endorsed-api</artifactId>
									<version>7.0</version>
									<type>jar</type>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<finalName>ListGenerator</finalName>
	</build>

</project>
```
**

**web.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd" version="3.1">
  <context-param>
    <param-name>javax.faces.PROJECT_STAGE</param-name>
    <param-value>Production</param-value>
  </context-param>
 <servlet-mapping>
     <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>*.jsf</url-pattern>
</servlet-mapping>
  <context-param>
    <param-name>primefaces.THEME</param-name>
    <param-value>bootstrap</param-value>
  </context-param>
  <servlet>
    <servlet-name>Faces Servlet</servlet-name>
    <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
  </servlet>
  <servlet-mapping>
    <servlet-name>Faces Servlet</servlet-name>
    <url-pattern>/faces/*</url-pattern>
  </servlet-mapping>
  <session-config>
    <session-timeout>60</session-timeout>
  </session-config>
  <welcome-file-list>
    <welcome-file>faces/login.xhtml</welcome-file>
  </welcome-file-list>
  <error-page>
      <exception-type>javax.faces.application.ViewExpiredException</exception-type>
      <location>/errorPage.xhtml</location>
  </error-page>
  <context-param>
    <param-name>BootsFaces_USETHEME</param-name>
    <param-value>true</param-value>
  </context-param>
</web-app>
```
**face-config.xml**
```xml
<?xml version='1.0' encoding='UTF-8'?>

<!-- =========== FULL CONFIGURATION FILE ================================== -->

<faces-config 
    xmlns="http://xmlns.jcp.org/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_2.xsd"
    version="2.2">
    <managed-bean>
        <managed-bean-name>listGeneratorGui</managed-bean-name>
        <managed-bean-class>be.slbo.listgenerator.ListGeneratorGui</managed-bean-class>
        <managed-bean-scope>session</managed-bean-scope>
    </managed-bean>
     <managed-bean>
        <managed-bean-name>IdentificationController</managed-bean-name>
        <managed-bean-class>Authentification.IdentificationController</managed-bean-class>
        <managed-bean-scope>session</managed-bean-scope>
    </managed-bean>
     <managed-bean>
        <managed-bean-name>dtColumnsView</managed-bean-name>
        <managed-bean-class>be.slbo.listgenerator.ColumnsView</managed-bean-class>
        <managed-bean-scope>session</managed-bean-scope>
    </managed-bean>
    

</faces-config>
```

**Comment by stephanrauh** [comment] 2015-12-31 11:00
It won't solve your problem, but I recommend you remove the duplicate servlet mapping from the web.xml. Mapping JSF to *.jsf does the trick, too. For some reason, many tutorials recommend the /faces/ mapping, but that's confusing nonsense in my eyes.

**Comment by stephanrauh** [comment] 2015-12-31 11:02
Another thing that isn't related to your problem: you can replace the bean definitions of the faces-config.xml by annotations. If you like the XML code, that's fine. However, most developers I know prefer the annotations (less keystrokes, more expressive code, less guesswork about the bean's scope etc.).

**Comment by atelyak** [comment] 2015-12-31 11:04
Thank you for your help.

**Comment by stephanrauh** [comment] 2015-12-31 11:07
At first glance, your code looks like it should help. I can't promise I manage it this year - but I'll try to reproduce your bug later.

Je vous souhaite une bonne et heureuse nouvelle année 2016!

**Comment by atelyak** [comment] 2015-12-31 11:12
Thank you very much.

No problem, currently i'm keeping the 0.6.6 version.

Happy New Year.

**Comment by stephanrauh** [comment] 2015-12-31 17:33
I've tried to reproduce your bug ... and everything runs fine. *Sigh*.

I've committed your code to my example repository. I suggest you check my test project out on your machine and tell me what the command button looks like. I had to remove two dependencies from your pom.xml - the oracle driver and the plugin dealing with the endorsed libraries folder - but other than that, our projects should be identical.

BTW: Do you want me to delete the demo project later? If not, I'd like to translate it to English and change the package names.

**Comment by atelyak** [comment] 2015-12-31 18:27
Hi,

Thank you.

I'm using Netbeans 8.x (i'm not at my work).
I don't know if netbeans cause that problem.
I will try to build on sts or eclipse.

I let you know monday.

Bye.

**Comment by atelyak** [comment] 2016-01-04 09:03
Hi,

Thank you very much for your help.
The project works like a charm in sts.
My app bug only with NetBeans 8.0.2

I have a other little problem in the log file when a use ajax call

That's the message showing in the log file:

-Event is null - probably that's a bug in AJAXRenderer, roughly line 100

![image](https://cloud.githubusercontent.com/assets/16499584/12086390/14b6d1c2-b2ca-11e5-92a1-f85b258460e5.png)

Is it normal ?

**Comment by atelyak** [comment] 2016-01-04 10:04
I have a other little problem in the log file when i use ajax call

That's the message appear in the log file i don't have this warning in bootsfaces 0.6.6:

-Event is null - probably that's a bug in AJAXRenderer, roughly line 100

![image](https://cloud.githubusercontent.com/assets/16499584/12086390/14b6d1c2-b2ca-11e5-92a1-f85b258460e5.png)

Is it normal ?
Ajax call is working good as 0.6.6 version but the message appear in the log.

**Comment by stephanrauh** [comment] 2016-01-04 18:57
You can safely ignore the log message. It's a left-over from an earlier stage of the implementation. At the time, it really would have indicated a bug, but I added new features in the meantime, so the situation can occur by using BootsFaces correctly. I'll remove the message ASAP.

**Comment by stephanrauh** [comment] 2016-01-04 18:58
As for your Netbeans problem: What happens if you build the *.war file manually using Maven->Install, and deploy it manually to the server?

**Comment by atelyak** [comment] 2016-01-04 20:16
Thank for all.

For netbeans, i have tried to build (via netbeans) manually and tested my project with an independant apache Tomcat but the results is the same.
i will try with maven -> install

Don't problem for me because, now, i prefer using STS instead Netbeans ;)

**Comment by stephanrauh** [comment] 2016-01-04 20:23
Yeah, if STS works fine for you, that's fine by me, too. But still, I'm a bit nervous about the dependency on a particular IDE. After all, if it happens to you, it can happen to other developers, too. So, yes, please test with mvn install :). 

Thanks in advance!
Stephan

P.S. I'm curious: which framework (if any) did you use for your data table? It resembles PrimeFaces. Is it?

**Comment by stephanrauh** [comment] 2016-01-09 09:42
This morning, I've installed Netbeans 8.1 and tried to reproduce your bug. Everything worked fine. The command button proudly shows its text. I'm puzzled.

**Comment by stephanrauh** [comment] 2016-01-09 09:58
Now I've also installed Netbeans 8.0.2 and it still works. I suspect there's something wrong with your Netbeans installation. Can you try to reproduce the bug on a different computer or using Netbeans 8.1 and report back? Thanks in advance!

I'll close this bug now because I don't think it's a problem of BootsFaces, but I still watch the ticket. Feel free to add your comments here.

**Closed by stephanrauh** 2016-01-09 09:58 UTC
Labels: User support

**Comment by atelyak** [comment] 2016-01-11 15:55
Yes i use the primefaces datatable (bootsrap theme).
I'm wainting for a full integrated datatable from bootsface with full reponsive design like primefaces 5.+.

The project working fine with netbeans 8.1.

I think my 8.0.2 version was corrupted.

Thank you very much for your help.
Best regards.

**Comment by stephanrauh** [comment] 2016-01-13 23:40
Also see #240. There was really a bug in the implementation of b:commandButton.

**Comment by microchest** [comment] 2016-05-20 07:32
Has this been fixed? I am also experiencing this problem when deployed on Tomcat 7/8 and JBoss. It works though on STS Pivotal TC server, which is on my local machine, and I wonder why. I am using version 0.8.0 because it seems to be stable except this bug.

What's also weird is that the value is showing in version 0.8.1, but the big problem is, it kinda submit the form twice simultaneously. I also tried putting ajax="false" because I assumed that if set to true, it will kinda execute an ajax request and together submits the form, but still it submitted twice.

`<b:commandButton ajax="false" styleClass="submit" value="#{ui.create_account}" action="#{userSignUpBean.signUp}" />`
