### ISSUE TITLE
ajax b:commandButton loses AJAX if onclick is used

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#750] opened 2017-05-03 11:01 UTC
This xhtml:
`<b:commandButton action="#{index.action}" value="Action" ajax="true" />`

Generates the following (as expected):
`<button type="submit" id="j_idt5:j_idt6" name="j_idt5:j_idt6" class="btn btn-default" onclick="BsF.ajax.callAjax(this, event,'j_idt5','j_idt5',null,null,null,null);;;return false;">Action</button>`

But when setting the `onclick` attribute...
`<b:commandButton onclick="alert(1)" action="#{index.action}" value="Action" ajax="true" />`
We get the following:
`<button type="submit" id="j_idt5:j_idt6" name="j_idt5:j_idt6" class="btn btn-default" onclick="alert(1);">Action</button>`

The `onclick` is overriden and the AJAX call is lost. The workaround is to set the ajax call by hand:
`<b:commandButton onclick="alert(1);ajax:index.action()" value="Action" ajax="true" />`

This also affects other AJAX components, like `inputText`: `<b:inputText value="hola" ajax="true" onchange="alert(1);" />`

**Comment by stephanrauh** [comment] 2017-05-03 17:25
I thought this is the expected behavior, but after checking what `b:commandButton` and `prime:commandButton` do, I agree with you that this is a bug.

**Comment by ggam** [comment] 2017-05-03 17:27
When I first saw it I couldn't classify it as a bug. But I didn't see it natural. If I set ajax to true, I expect the form to be submitted via ajax, independently of any other events.

**Comment by stephanrauh** [comment] 2017-05-03 21:01
I frequently to something like `onclick="if (condition) return false;"`.  This snippet prevents the AJAX call conditionally. So it's a bit surprising I didn't chain the original AJAX call to the user-define JavaScript snippet.

**Comment by ggam** [comment] 2017-05-22 13:31
This is causing the following issues:
- `oncomplete` doesn't work, as it just registers a callback for the `action` AJAX call, which is not rendered
- JSF navigation only works for form actions. If you want a redirection as a result of the request, (calling a method returning a String), navigation won't be triggered for the `onclick` calls.

The workaround is manually making the AJAX request on the onclick using BootsFaces APIs, like if it was rendered from the `action`.

**Comment by stephanrauh** [comment] 2017-05-22 19:28
IMHO we should chain the JavaScript and the AJAX call, just like Mojarra, MyFaces and PrimeFaces do it. We just haven't started to do so :).

**Comment by sutteth1** [comment] 2017-11-17 08:33
+1

**Comment by t-oster** [comment] 2018-11-28 13:41
+1

**Comment by t-oster** [comment] 2018-11-28 13:43
I also stumeled on this bug and it was not clear to me. I first used <b:commandButton with some action and ajax set to true. Then I wanted to have an (client side) onclick action, but suddenly the button did not use ajax anymore. So at least if the onclick attribute does not use any serverside ajax calls, this is clearly a bug.

**Comment by t-oster** [comment] 2018-11-28 13:46
For clarification:
```xhtml
<!-- uses ajax as expected -->
<b:commandButton action="#{myBean.doSomething}" ajax="true" />
<!-- Does NOT use ajax, but should -->
<b:commandButton action="#{myBean.doSomething}" ajax="true" onclick="console.log('wtf')"/>
<!-- Workaround until this is fixed -->
<b:commandButton  onclick="console.log('wtf');ajax:myBean.doSomething()"/>

**Comment by vsvetoslavov** [comment] 2019-04-11 09:12
I see one thing here worth checking in @t-oster 's example above
```
<!-- Does NOT use ajax, but should -->
<b:commandButton action="#{myBean.doSomething}" ajax="true" onclick="console.log('wtf')"/>
```
It is not clear whether `console.log('wtf');` should be called before or after the ajax event - therefore the workaround seems easier to understand.

**Comment by stephanrauh** [comment] 2019-04-12 21:35
I agree that the workaround is easier to understand. That's why I invented `ajax:some.method()` in the first place. :) But even this workaround might be confusing. You have to keep in mind that `ajax:what.ever()` starts the call of `what.ever()` without waiting for the result. Every JavaScript programmer should know that, but there's no reason to assume every Java programmer is familiar with this pattern.

**Comment by t-oster** [comment] 2019-04-13 09:16
When using ajax in the onclick listener, I agree it is not clear, however if just using plain JS I would have assumed that it behaves like the usual on click handler,meaning the JS is evaluated first and after that the usual action is performed (as it already works with ajax=false)

**Comment by t-oster** [comment] 2019-10-22 08:18
What is the state of this issue? Is there any reason not to chain the user submittet 'onclick' with the javascript from the action? Maybe even only if the onclick evaluates to true. The current workaround is not very beautiful, does not work with autocomplete in most IDEs. I do not see any disadvantage in chaining.

**Comment by bytecode-seller** [comment] 2021-12-24 21:58
I think this project is abandoned. The real workaround is this:

`onclick="if(!confirm(‘Do you really want to delete this item?')) return false; ajax:catalogSatEstController.delete();javascript:return false;”`

Both `return false` commands prevent page refresh and/or unwanted post while letting do required bean call.

**Comment by t-oster** [comment] 2021-12-29 09:11
@TheCoder4eu will you accept a pull request, which changes that behavior? If I find the time, I am willing to contribute this, but I want to be sure it will be merged.

**Comment by TheCoder4eu** [comment] 2022-01-06 10:54
Hi @t-oster ,
sorry for the late answer, yes your contribution is very appreciated, so please go ahead with the pull request and we will merge it after a quick review!

**Comment by TheCoder4eu** [comment] 2022-01-09 16:31
@t-oster ,
I forgot to add that we'd like to release v1.6.0 soon :-)

**Comment by t-oster** [comment] 2022-01-10 09:27
The underlying issue is in AjaxRenderer.generateBootsFacesAJAXAndJavaScript https://github.com/TheCoder4eu/BootsFaces-OSP/blob/734833d058bb1bd0117e8c549be119f357dab425/src/main/java/net/bootsfaces/component/ajax/AJAXRenderer.java#L180 method:
It first calls `generateAJAXCallForASingleEvent` here https://github.com/TheCoder4eu/BootsFaces-OSP/blob/734833d058bb1bd0117e8c549be119f357dab425/src/main/java/net/bootsfaces/component/ajax/AJAXRenderer.java#L191, which calls the `ResponseRenderer.renderAttribute` method with the original `onclick` attribute.
Afterwards it generates the correct javascript and again calls the `ResponseRenderer.renderAttribute` method here https://github.com/TheCoder4eu/BootsFaces-OSP/blob/734833d058bb1bd0117e8c549be119f357dab425/src/main/java/net/bootsfaces/component/ajax/AJAXRenderer.java#L240, but that seems to have no effect (probably the attribute is only added on the first call).

I could inject a Decorator for the ResponseRenderer class, which caches all renderAttribute calls and overwrites previous versions with later ones, but this does not make the code very readable.

On the other hand I cannot see an easy way to swap the order of the calls, because the first call determines if the onclick handler already includes ajax.

**Comment by t-oster** [comment] 2022-01-10 14:40
I have a better idea, will update the PR tomorrow: if A
ajax = true, and no `ajax:` is used in the onclick handler, just skip the first writeAtttibute call. Are there any unit tests?

**Comment by qbtcoder** [comment] 2022-01-10 20:25
Hi @t-oster ,
thank you for your PR!
We'll wait for the update, unfortunately there are no unit tests.

**Comment by t-oster** [comment] 2022-01-12 06:07
The second version is probably easier to read.

**Closed** 2022-01-23 17:33 UTC
Labels: bug, confirmed
