### ISSUE TITLE
f:ajax delay not respected

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#955] opened 2018-06-17 18:07 UTC
given this xhtml code sample i would expect the action to be called 1 second after the user stops writing
```xml
<b:inputText
	value="#{myBean.value}">
	<f:ajax event="keyup" delay="1000"
	listener="#{myBean.action}" render="@form"
	execute="@this" />
</b:inputText>
```
backing bean action function
```java
public void action(AjaxBehaviorEvent e) {
	System.out.println("FIRED");
}
```
seems to work ok with `h:inputText`.   i am using MyFaces 2.2

**Comment by stephanrauh** [comment] 2018-06-19 20:59
What happens instead? Is the AJAX request sent immediately?

Does the error occur only with `f:ajax`? It's possible I've only implemented the BootsFaces style:

```html
<b:inputText placeholder="Type something here..." value="..."
                      onkeyup="ajax:inputTextBean.capitalizeText()" update="@next" delay="1000"/>
```

**Comment by chongma** [comment] 2018-06-20 09:44
yes the request is sent immediately on keyup.  i will try with the delay attribute and let you know

**Comment by chongma** [comment] 2018-06-20 09:53
no it still seems to be sending the request immediately.  here is the code in case i did something wrong
```xml 
<b:inputText label="Spacing" value="#{comparisonBean.comparison.viewerSettings.spacing}" 
rendered="#{comparisonBean.comparison.viewerSettings.sideBySide}"
 onkeyup="ajax:comparisonBean.action()" delay="1000" update="@form" />
```
and the bean
```java
@Transactional
public String action() {
	setComparison(comparisonDao.update(getComparison()));
	FacesContext context = FacesContext.getCurrentInstance();
	FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO, "Success", "Updated");
	context.addMessage(null, facesMessage);
	return null;
}
```

**Comment by stephanrauh** [comment] 2018-06-24 19:07
@chongma Doesn't look wrong at first glance. Strange. I've pushed the showcase demo of `delay`. Have a look here: https://github.com/TheCoder4eu/BootsFacesWeb/blob/a1274a535914e0a631a7e0ac22e205e245c37bc8/src/main/webapp/forms/inputText.xhtml#L48

**Comment by chongma** [comment] 2018-06-24 22:02
@stephanrauh  i have pulled bootsFacesWeb and the showcase example does seem to be working fine.  i will take another look my end.  maybe it is because i am using CDI instead of EJB?

**Comment by chongma** [comment] 2018-06-27 06:43
i am also using MyFaces.  if I remember rightly BootsFacesWeb imports Mojarra.  maybe we should have different profiles for MyFaces and Mojarra

**Comment by stephanrauh** [comment] 2018-06-27 20:37
We do. There's a profile for MyFaces 2.2.10 and a profile for Mojarra 2.2.11. I'm just lazy about testing MyFaces. Oh, and you're right, by default the core library is compiled with a profile called "Mojarra". But in reality, it's just the API taken from the JSF 2.2 spec. What really counts is the profile of the BootsFacesWeb project.

I'd also like to add a JSF 2.3 profile - but that seems to be difficult because I don't know how to use JSF 2.3 with Tomcat. Any suggestions?

**Comment by stephanrauh** [comment] 2018-06-27 20:39
BTW, I don't believe that using EJBs solves the problem. JSF uses either `@ManagedBean`s or `@Named` beans, but it doesn't have a clue what to do with an EJB.

**Comment by chongma** [comment] 2018-06-28 08:58
if i set MyFaces profile as the default when i access BootsFacesWeb i get 
```
javax.servlet.ServletException: com/sun/faces/facelets/tag/MethodRule
	javax.faces.webapp.FacesServlet.service(FacesServlet.java:230)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
```

**Comment by stephanrauh** [comment] 2018-06-28 18:55
Oh. It seems that the showcase doesn't start with MyFaces 2.2.10. There's an arcane error message:

**Comment by stephanrauh** [comment] 2018-06-28 18:57
Yes, I can confirm that. Weird. @tandraschko When you tested BootsFaces with MyFaces 2.3, did you use any setting we've forgotten? Like a missing dependency in the pom.xml, or configuring an EL resolver in the web.xml?

**Comment by tandraschko** [comment] 2018-06-28 19:00
It also works fine with MF2.3: https://github.com/primefaces/primefaces-test

**Comment by tandraschko** [comment] 2018-06-28 19:31
Looks like there is a taglib in the CP which uses the com/sun/faces/facelets/tag/MethodRule.

Check your libs and dependencies.

**Comment by stephanrauh** [comment] 2018-06-28 19:52
Now that you say it - right you are! The offending library is HighFaces. Just remove it from the pom.xml, and the showcase works again (apart from the HighFaces demo).

**Comment by stephanrauh** [comment] 2018-06-28 19:56
Back to the original topic: the delay attribute works fine with the BootsFaces showcase running on MyFaces 2.2.10.

**Comment by chongma** [comment] 2018-07-03 13:11
i am using
```xml
<context-param>
      <param-name>net.bootsfaces.blockUI</param-name>
        <param-value>true</param-value>
    </context-param>
```
when i add this to the showcase web.xml then it breaks the `delay`

**Comment by stephanrauh** [comment] 2018-07-03 20:36
Sounds like a firm lead. I have to admit I didn't try this combination yet.

**Comment by chongma** [comment] 2018-07-12 09:45
@stephanrauh the only part i see about blockUI is in AddResourcesListener.addJavascript
```java
String blockUI = BsfUtils.getInitParam(P_BLOCK_UI, context);
		if (null != blockUI)
			blockUI = ELTools.evalAsString(blockUI);
		if (null != blockUI && isTrueOrYes(blockUI)) {
			createAndAddComponent(root, context, SCRIPT_RENDERER, "js/jquery.blockUI.js", C.BSF_LIBRARY);
		}
```

**Comment by stephanrauh** [comment] 2018-07-29 13:44
I've added the BlockUI parameter to the web.xml and started the showcase running on MyFaces. The AJAX event is still processed after a second. However, BlockUI blocks the UI immediately, so adding the `delay` attribute is pointless.

**Comment by stephanrauh** [comment] 2018-07-29 14:08
After debugging the JavaScript source code, I found out that the delay attribute calls the Java bean in a timeout:

![image](https://user-images.githubusercontent.com/3045767/43367178-6a3057d8-9349-11e8-854d-9a02e2ab9727.png)

So everything seems to be OK from our side. 

@chongma Can you debug jsf.js.jsf?ln=javax.faces, too, and check if your system reacts differently?

**Comment by stephanrauh** [comment] 2018-07-29 14:39
I've moved the BlockUI code to a more sensible position. I've also uploaded a new developer snapshot of BootsFaces 1.3.1 to Maven Central. I can only guess, but chances are the bug is now fixed. In any case, the combinations of BlockUI and delayed AJAX requests is more useful now.

**Comment by chongma** [comment] 2018-07-30 21:48
updating to 1.3.1-SNAPSHOT gives me this error when i update certain areas of my webapp using ajax.  i am not sure what causes the duplicate id because the error stops the page from being loaded.  there is no component with that id before the commandButton is clicked
```
org.apache.myfaces.view.facelets.compiler.DuplicateIdException: Component with duplicate id "j_id__v_23" found. The first component is {Component-Path : [Class: javax.faces.component.UIViewRoot,ViewId: /admin/file.xhtml][Class: org.apache.myfaces.component.ComponentResourceContainer,Id: javax_faces_location_head][Class: javax.faces.component.UIOutput,Id: j_id__v_23]}
	at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.createAndQueueException(CheckDuplicateIdFaceletUtils.java:152)
	at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:107)
	at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:124)
	at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:124)
	at org.apache.myfaces.view.facelets.compiler.CheckDuplicateIdFaceletUtils.checkIds(CheckDuplicateIdFaceletUtils.java:89)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.saveView(DefaultFaceletsStateManagementStrategy.java:738)
	at org.apache.myfaces.application.StateManagerImpl.saveView(StateManagerImpl.java:213)
	at javax.faces.application.StateManager.getViewState(StateManager.java:263)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartialRendering(PartialViewContextImpl.java:584)
	at org.apache.myfaces.context.servlet.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:415)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
	at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:85)
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:144)
	at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:516)
```

**Comment by chongma** [comment] 2018-10-15 16:00
@stephanrauh it doesn't work in 1.3.0.  i have a mave profile to run 1.3.1-SNAPSHOT but that was the one that gave me the above error.  which version should i be testing?

**Comment by chongma** [comment] 2018-10-15 16:29
@stephanrauh i just tested with 1.3.1-SNAPSHOT again and i get the same duplicate component id message with `b:inputText`.  switching back to `h:inputText` gets rid of the problem.  the xhtml i am using is
```
<b:inputText value="#{paymentBean.fileId}" autocomplete="off">
	<f:ajax event="keyup" delay="1000"
		listener="#{paymentBean.search}" render="searchPanel"
		execute="@this" />
</b:inputText>
```

**Comment by stephanrauh** [comment] 2018-10-15 21:04
Somehow I missed the error description. Duplicate id - that's weird. IMHO, your code snippet doesn't look that different from our showcase. What do I miss?

**Comment by stephanrauh** [comment] 2018-10-15 21:08
BTW, I've just published BootsFaces-1.4.0-SNAPSHOT to Maven Central. But I don't think it doesn't much of a difference. I didn't modify the AJAX engine for months.

**Comment by chongma** [comment] 2018-10-15 21:09
i will try to create a simple reproducer

**Comment by stephanrauh** [comment] 2019-08-03 13:00
Any news on this? I'd like to close the ticket.

**Closed by stephanrauh** 2019-08-03 13:00 UTC
Labels: bug
