### ISSUE TITLE
b:commandButton not calling method from action="#{bean.method()}"  when in the same <h:form> as an <h:inputFile> in 0.8.5

### ISSUE THREAD

**Issue by Robblle** [TheCoder4eu/BootsFaces-OSP#376] opened 2016-05-11 17:02 UTC
After creating a ValidatorExceptions or getting an "InputField required Exceptions" by clicking the "Save Changes" button all commandButtons within the same form stop working as long as there's a <h:inputFile>, <p:fileUpload> or standard html <input type="file"/> in the same form.

```
<h:form id="form" enctype="multipart/form-data">
<h:inputFile id="inputFile" value="#{editProfile.file}"/>
<b:inputText id="name" value="#{editProfile.vorname}" validator="#{editProfile.validateName}" required="true"  requiredMessage="Username required/">
<h:message id="mname" for="name" style="color:red;margin:0px;"/>
<b:commandButton ajax="false" update="mname" action="#{editProfile.saveChanges()}"
value="Save Changes" />
<b:commandButton ajax="false" immediate="true" value="Back" action="#{editProfile.back()}"/>
</h:form>
```
When I replace the `<b:commmandButton>` with a primeFaces `<p:commandButton>` it works.

Browser: Google Chrome 50.0.2661.94
OS: Windows 7 Home Premium

**Comment by zhedar** [comment] 2016-05-11 17:52
I couldn't reproduce the field required problem. It seems like it works like intended. (Although I currently skipped the validator and the inputfile, does it still now work without these for you?)

Your example also didn't work as provided (there no field `name` like referenced, only `vorname`). I guess this is just a copy / paste problem though.

**Comment by Robblle** [comment] 2016-05-11 18:02
The inputfile is what causes this problem. If you move it outside the <h:form> everything works as intended.

**Comment by zhedar** [comment] 2016-05-11 18:08
Tried the `h:inputFile` as well. Sadly still couldn't reproduce. Although I'm currently running 0.9.0-SNAPSHOT, will try with the 0.8.5 release now.

**Comment by Robblle** [comment] 2016-05-11 18:16
The error also occurs if the inputField is empty and required set to true.

**Comment by stephanrauh** [comment] 2016-05-11 22:18
I've assigned this issue to version 0.9.0, but it looks like a candidate for 0.8.6. But of course we have to reproduce the error before we can fix it.

**Comment by zhedar** [comment] 2016-05-12 10:15
@Robblle  I think a minimal example is better than a bigger one. Since I couldn't reproduce the first, I would like to know which JSF implementation you are using. MyFaces? Mojarra?

**Comment by Robblle** [comment] 2016-05-12 11:50
I'm using Mojarra.

**Comment by stephanrauh** [comment] 2016-05-21 12:43
I didn't see any difficulties with your example, no matter if you use AJAX or not. Note that your `update` attributes override the `ajax="false"` attribute in your example. This is my example code:

```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Login</title>
        <meta charset="UTF-8"/>
    </h:head>
    <h:body>
        <b:jumbotron>

            <h:form id="form" enctype="multipart/form-data">
                <b:container fluid="false">
                    <b:growl id="message" showDetail="true" />

                    <h:inputFile id="inputFile"/>

                    <b:row>
                        <b:column col-xs="12" col-sm="12" col-md="2" offset="3"><h:outputText value="Username:" /></b:column>
                        <b:column col-xs="12" col-sm="12" col-md="4">
                            <b:inputText id="username" value="#{loginBean.username}" required="true" requiredMessage="Username required">
                                <f:facet name="prepend">
                                    <b:iconAwesome name="fa-user" style="width: 1em;" />
                                </f:facet>
                            </b:inputText>
                        </b:column>

                    </b:row>

                    <b:row>
                        <b:column col-xs="12" col-sm="12" col-md="12" offset="3">
                            <h:message id="musername" for="username" style="color:red;margin:0px;"/>
                        </b:column>
                    </b:row>

                    <b:row>
                        <b:column col-xs="12" col-sm="12" col-md="2" offset="3"><h:outputText value="Password:" /></b:column>
                        <b:column col-xs="12" col-sm="12" col-md="4">
                            <b:inputSecret id="password" value="#{loginBean.password}" required="true" requiredMessage="Password required">
                                <f:facet name="prepend">
                                    <b:iconAwesome name="fa-key" style="width: 1em;"/>
                                </f:facet>
                            </b:inputSecret>
                        </b:column>
                    </b:row>

                    <b:row>
                        <b:column col-xs="12" col-sm="12" col-md="12" offset="3">
                            <h:message id="mpassword" for="password" style="color:red;margin:0px;"/>
                        </b:column>
                    </b:row>

                    <b:row/>
                    <b:row>
                        <b:column col-xs="12" col-sm="12" col-md="4" offset="4">
                            <b:commandButton value="Login" id="btnLogin" action="#{loginBean.login()}" ajax="false" styleClass="btn btn-primary"
                                             style="width: 100%;" />
                        </b:column>
                    </b:row>
                </b:container>
            </h:form>
        </b:jumbotron>
    </h:body>
</html>
```

```java
package net.bootsfaces.demo;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

@ManagedBean
@ViewScoped
public class LoginBean {
	@Size(min=4, max=10)
	@NotEmpty
	private String username;

	@Size(min=4, max=10)
	@NotEmpty
	private String password;


	public void setUsername(String name) {
		this.username = name;
	}

	public String getUsername() {
		return username;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}

	public void login() {
		if ("BootsFaces".equalsIgnoreCase(username) && "rocks!".equalsIgnoreCase(password)) {
			FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Congratulations! You've successfully logged in.", "");
			FacesContext.getCurrentInstance().addMessage("loginForm:password", msg);

		} else {
			FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "That's the wrong password. Hint: BootsFaces rocks!", "");
			FacesContext.getCurrentInstance().addMessage("loginForm:password", msg);
		}
	}

	public void forgotPassword() {
		FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Default user name: BootsFaces", "");
		FacesContext.getCurrentInstance().addMessage("loginForm:username", msg);
		msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Default password: rocks!", "");
		FacesContext.getCurrentInstance().addMessage("loginForm:password", msg);
	}
}
```

**Comment by Robblle** [comment] 2016-05-22 11:44
It seems removing the update tag from the `<b:commandButton>` solved this issue for me. It is still odd to me that primefaces buttons work with the update tag and the bootsfaces ones don't. Also, thank you for helping me out.

**Comment by stephanrauh** [comment] 2016-05-22 17:29
Well, your PrimeFaces version didn't use the `update` attribute because you switched ajax explicitly off :). 

It's a pity we didn't manage to reproduce the bug. It feels like there's a known bug out there we can't solve. I close the issue nonetheless.

**Closed by stephanrauh** 2016-05-22 17:29 UTC
Labels: User support
