### ISSUE TITLE
<b:selectOneMenu> validation: "bf-error" CSS problems

### ISSUE THREAD

**Issue by danysion** [TheCoder4eu/BootsFaces-OSP#593] opened 2016-12-22 12:59 UTC
When I use required validation in <b:selectOneMenu> and this throws an error, the class "bf-error" doesn't apply in my component.
I need help, thanks so much.

```xml
<b:selectOneMenu rendered="#{Expedients.suas}" required="true" tooltip="#{gecohMsg['container.combo.sua.tooltip']}"
	requiredMessage="#{gecohMsg['message.requiredField']}"
	id="contentComboSua" value="#{Expedients.facadeTableSelect.sua}"
	disabled="#{Expedients.disabledFields}">
	<f:selectItems value="#{Expedients.comboSua}" var="sua"
		itemLabel="#{sua.value}" itemValue="#{sua.code}" />
</b:selectOneMenu>
```
I have encountered a similar problem in this git : https://github.com/TheCoder4eu/BootsFaces-OSP/issues/449

**Comment by stephanrauh** [comment] 2016-12-22 21:11
I take it that "this throws an error" doesn't refer to a technical error, such as a `NullPointerException`, but to a violated validation constraint? If so, your bug report is an exact duplicate of #449.

**Comment by stephanrauh** [comment] 2016-12-22 22:32
Oh. I see. Actually, the component works as designed, but the design wasn't good enough. Let's clarify this, just in case. I've designed the component in such a way that the class of the label is modified according to the state of the `b:selectOneMenu`. I've marked this with a green frame in the screenshot below. But I forgot to update the CSS class of the `b:selectOneMenu` itself (red). Is that the error you're reporting?

![image](https://cloud.githubusercontent.com/assets/3045767/21442517/8b7f7eae-c89e-11e6-89bc-f0c465de4925.png)

**Comment by stephanrauh** [comment] 2016-12-22 22:33
Also see the live preview at http://www3.bootsfaces.net/Showcase/forms/selectOneMenu.jsf#errorClasses. 

Thanks in advance,
Stephan

**Comment by danysion** [comment] 2016-12-23 06:19
Exactly that is the problem that we have, the <b: selectOneMenu> component never turns red and does not change its classes.

**Comment by danysion** [comment] 2016-12-23 06:21
I would need the error style to follow a standard, to put the component itself in red color not the label.

**Comment by stephanrauh** [comment] 2016-12-23 20:23
OK, that's something we can care about. Probably every input field is affected. Let's check them all, one by one:
- [ ] b:inputText
- [ ] b:colorPicker
- [ ] b:selectOneMenu
- [ ] b:selectMultiMenu
- [ ] b:datepicker
- [ ] b:dateTimePicker

**Comment by stephanrauh** [comment] 2016-12-26 20:19
Whow. Solving this bug revealed quite a few bugs that managed to hide during our tests. Thanks for opening and reporting the bug!

**Closed by stephanrauh** 2016-12-26 20:19 UTC
Labels: bug, confirmed

**Comment by stephanrauh** [comment] 2016-12-30 18:55
You can run a test using the BootsFaces-1.1.0-SNAPSHOT on Maven Central. See #369 on how to get it.
