### ISSUE TITLE
dateTimePicker minDate "Unexpected identifier"

### ISSUE THREAD

**Issue by MitchTalmadge** [TheCoder4eu/BootsFaces-OSP#506] opened 2016-09-16 05:21 UTC
I am trying to use `b:dateTimePicker` and having very little luck. Here is my code:

```xml
<b:dateTimePicker showDate="true" showTime="true" format="MM/DD/YYYY h:mm a"
                  minDate="#{timeSelectionController.minDateTime.toDate()}"
                  value="#{searchByTimeController.startTime}"/>
```

the minDateTime getter is simply: (Using joda time)

```java
public DateTime getMinDateTime() {
    return new DateTime();
}
```

The picker shows up:
![image](https://cloud.githubusercontent.com/assets/8848080/18576047/02fc8f36-7b9b-11e6-854e-6ea63594f364.png)

But clicking on it does nothing and I get this in the console on page load:
![image](https://cloud.githubusercontent.com/assets/8848080/18576060/1a1ae942-7b9b-11e6-9a31-39a32205808c.png)

Am I doing something wrong?

**Comment by MitchTalmadge** [comment] 2016-09-16 05:25
For the record, the value doesn't appear to be the problem -- setting it to null has the same effect.

**Comment by asterd** [comment] 2016-09-16 07:56
Hi @MitchTalmadge,

the problem is related to two main things:
1. A little bug inside the code that I've just fixed and committed to the repo.
2. Another little bug in your code (at least in my local test): if you set the minDate as the "toDate()" value, it returns a format that moment does not recognize (eg. 'Fri Sep 16 09:31:23 CEST 2016'). You must fix that.

I hope I've helped you.

**Comment by MitchTalmadge** [comment] 2016-09-16 17:23
Alright, here is my new code which prevents the error from being thrown, but does not perform the function I expect:

```xml
<b:dateTimePicker format="MM/DD/YYYY h:mm a"
minDate="'#{timeSelectionController.dateTimePickerMinDate}'"
value="#{searchByTimeController.startTime}"/>
```

Here is the minDate now:
```java
return new SimpleDateFormat("MM/dd/yyyy h:mm a").format(getMinDateTime().toDate());
```

(I added single quotes to minDate until the new code with your fix is released)

This works, except that the min date appears to have no effect at all on the picker. I can still select previous days and times on the calendar:

Actual calendar:
![image](https://cloud.githubusercontent.com/assets/8848080/18594955/ae931446-7bff-11e6-8bdc-8d7004b0e189.png)

Javascript: (notice the min date)
![image](https://cloud.githubusercontent.com/assets/8848080/18594963/bb75bb82-7bff-11e6-8836-460438ba31f3.png)


Also, just to point out, the website does say for minDate that it "Accepts: date, moment, string.", so I feel in a way that me using a date is not my fault, but rather that the component renderer should format the date based on the provided format attribute.

**Comment by asterd** [comment] 2016-09-16 17:38
You were right! But the component is still in progress and i've to find the time to end it.. Anyway thanks for you issue! I'll try work on that asap!

**Comment by MitchTalmadge** [comment] 2016-09-17 03:17
I found out if you remove the square brackets from the minDate, it works as expected. https://jsfiddle.net/1rd1p3f9/

**Closed** 2016-09-17 23:54 UTC
