### ISSUE TITLE
Closing a b:dropMenu and/or selecting an item in a b:dropMenu makes it disappear

### ISSUE THREAD

**Issue by wsaxton** [TheCoder4eu/BootsFaces-OSP#116] opened 2015-06-21 14:11 UTC
Very simple.  I put the sample code (below) into a facelets page and tried using the dropMenu.  If you close the menu or select something from the menu, the entire dropmenu disappears. (style attrbutes gets "display: none").

I'm using version .66.  Not sure if this is fixed in later versions, but this is the latest version from the maven repository.  I don't see this behavior in the component showcase though...so not sure what's going on.

    <b:navBar brand="Brand" brandHref="#">
    <b:navbarLinks>
        <b:navLink value="Home" href="#"></b:navLink>
        <b:navLink value="Link" href="#"></b:navLink>
        <b:navLink value="Link" href="#"></b:navLink>
        <b:dropMenu value="Dropdown">
            <b:navLink value="Action" href="#"></b:navLink>
            <b:navLink value="Another action" href="#"></b:navLink>
            <b:navLink value="Something else here" href="#"></b:navLink>
            <b:navLink></b:navLink>
            <b:navLink header="Nav header"></b:navLink>
            <b:navLink value="Separated link" href="#"></b:navLink>
            <b:navLink value="One more separated link" href="#"></b:navLink>
        </b:dropMenu>
    </b:navbarLinks>
    </b:navBar>

**Comment by wsaxton** [comment] 2015-06-21 16:28
It looks like this is an issue with ICEfaces 3.3.  I removed that dependency and it works fine.

Any ideas how this could break this?

**Comment by wsaxton** [comment] 2015-06-21 17:03
It looks like it's, specifically, the icefaces-compat library which contains the ICEfaces ice tags.

    <dependency>
        <groupId>org.icefaces</groupId>
        <artifactId>icefaces-compat</artifactId>
        <version>3.3.0</version>
    </dependency>

**Comment by stephanrauh** [comment] 2015-06-21 17:13
This particular incompatibility comes as a surprise. Just to be sure: the menu vanishes even if you don't trigger a request?

BTW, since yesterday the latest version is 0.7.0 :).

**Comment by stephanrauh** [comment] 2015-06-21 17:42
Confirmed:
* adding org.icefaces:icefaces:3.3.0 to the dependencies break the resource loader. Nothing will work.
* adding both org.icefaces:icefaces:3.3.0 and org.icefaces:icefaces-compat:3.3.0 converts our showcase to modern art, Picasso style. The vanishing menus are just one issue - actually, a minor one.

**Comment by stephanrauh** [comment] 2015-06-21 17:55
The HTML code generated by the b:dropMenu looks a bit odd. There's at least one li tag that's opened but never closed.

**Comment by wsaxton** [comment] 2015-06-21 17:56
BTW, in case people want a workaround:

    .dropdown {
        display: block !important;
    }

Seems to do the trick. Not sure why the display has to be effected @ all by this component but...

**Comment by wsaxton** [comment] 2015-06-21 17:57
> This particular incompatibility comes as a surprise. Just to be sure: the menu vanishes even if you don't trigger a request?

It only appears to happen when I trigger the "collapse" of the dropMenu or select one of the items in the menu.

**Comment by stephanrauh** [comment] 2015-06-21 18:09
Yeah, I managed to reproduce the error in the meantime. I guess there are two problems:
* The invalid HTML code confuses ICEFaces (especially the automatic AJAX feature).
* ICEFaces brings a couple of CSS files that are incompatible with BootsFaces.

The result really looks interesting - even if it's not quite what it should look like:
![image](https://cloud.githubusercontent.com/assets/3045767/8272780/47a16b10-1851-11e5-8208-02b2a014f030.png)

**Comment by stephanrauh** [comment] 2015-06-23 20:34
After fixing a couple of minor bugs of the generated HTML code, things look a lot better. I suspect the "automatic AJAX" engine reacts a bit nervous if it detects HTML code it can't parse. There's still work left to do: a few components still can't be rendered with ICEFaces.

![image](https://cloud.githubusercontent.com/assets/3045767/8316527/fe00ca98-19f7-11e5-96e9-e78382d31a61.png)

**Comment by stephanrauh** [comment] 2015-11-07 22:04
Frankly, ICEFaces support isn't a high priority to me. Let's admit we're incompatible and close this issue. BTW, compatibility has improved with BootsFaces 0.8.0.

**Closed by stephanrauh** 2015-11-07 22:04 UTC
Labels: bug, issue with other JSF fwk
