### ISSUE TITLE
 method loaded in  all navlink

### ISSUE THREAD

**Issue by mostfa-ayad** [TheCoder4eu/BootsFaces-OSP#269] opened 2016-01-22 19:20 UTC
i use one page for edit  object and insert new   and  i use reset method  to reload object i try to
use the oncomplete to  handle this  but  this  method loaded in  all navlink
```xml
<b:navLink value="تعديل" update="@form @(.content)"
                  onclick="ajax:journalMovePage.setPage('edit.xhtml')" />
<b:navLink value="جديد" update="@form @(.content)"
                  onclick="ajax:journalMovePage.setPage('edit.xhtml')" 
                  oncomplete="#{journalMovePage.reset()}" />
```

**Comment by mostfa-ayad** [comment] 2016-01-22 19:39
i  do  it  by  handle  it  in  the  set method   it done now

**Comment by stephanrauh** [comment] 2016-01-22 20:47
Before answering your question, let's make sure I got your question.

* I suppose you're writing a single-page application using BootsFaces AJAX.
* There's a page serving two purposes. First, `edit.xhtml` allows users to edit an existing object. Second, the same page `edit.xhtml` allows users to create a new object.
* The difference is that you call `journalMovePage.reset()` to clear every input field (probably including the primary key). This, in turn, activates the "insert new item" mode.
* You've tried to call the `...reset()` method in an `oncomplete` handler, but to no avail. It wouldn't work.
* You've solve your problem by moving the call to `reset()` into the `...setPage()` method.

**Comment by stephanrauh** [comment] 2016-01-22 20:54
Well... first thing you need to know is that JSF executes method calls followed by brackets at rendering time. So `oncomplete="#{journalMovePage.reset()}` doesn't do what you want it to do. Instead of calling ' reset()´ after `setPage()`, it's called a lot earlier, when the page is rendered.

You could solve this by writing `oncomplete="ajax:journalMovePage.reset()"` (although I have to admit I'm not sure I implemented this yet).

Second, you need to know that the `oncomplete` is called after sending the response back to the client. In other words: no matter what `oncomplete` does on the server, the page shown in the browser won't change because it has already been painted.

I hope that helps you. Please give us feedback. Do we have to improve the documentation?

**Comment by mostfa-ayad** [comment] 2016-01-23 16:44
i will  try but  i have an error
Unable to find resource bsf, css/default/icons.css

**Comment by stephanrauh** [comment] 2016-01-30 20:19
I believe you can safely ignore the first error message ("Unable to find resource bsf, css/default/icons.css"). Its only a problem if your Font Awesome icons aren't rendered. We'll investigate this error nonetheless, but it shouldn't harm you applications.

The second warning is caused by OmniFaces and has been fixed in summer or autumn. The current 2.x branch of OmniFaces doesn't show this message. In any case, you can safely ignore this message, too. It doesn't affect your application negatively. Plus, in production mode, the message is not shown.

**Closed by stephanrauh** 2016-01-30 20:19 UTC
Labels: User support, Waiting for user answer
