### ISSUE TITLE
last panel in <b:carousel> wizard component doesn't show when clicked 'next' command button has an action method

### ISSUE THREAD

**Issue by yasinkasap** [TheCoder4eu/BootsFaces-OSP#504] opened 2016-09-12 18:47 UTC
Hi,

I have a `<b:carousel>` wizard styled component. I want to add two numbers from input text in first two steps and to show summary in last step. Adding numbers is doing by action method in mb. The method bounds to carousel's 'next' command button. When carousel's active step is step to, when i clicked next button I expect pass to step three bu did not. The step still staying step two.Could you help me ?

xhtml page :

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:b="http://bootsfaces.net/ui">
<h:head></h:head>
<h:body>
	<ui:composition template="../common.xhtml">
		<ui:define name="title">Title</ui:define>
		<ui:define name="content">
			<h:form>
				<b:carousel id="wizard" styleClass="wizardPseudoClass"
     style="width:400px;height:350px;padding-top:20px"
     startAnimation="false"
     showIndicators="false"
     wrap="false">
     <b:carouselItem style="width:400px;height:230px">
       <b:panel title="Step 1" look="primary">
         <b:inputText label="Number One" value="#{sampleMb.number1}" renderLabel="true"/>
       </b:panel>
     </b:carouselItem>
     <b:carouselItem style="width:400px;height:230px">
       <b:panel title="Step 2" look="danger  ">
         <b:inputText label="Number Two" value="#{sampleMb.number2}" renderLabel="true"/>
       </b:panel>
     </b:carouselItem>
     <b:carouselItem style="width:400px;height:230px">
       <b:panel title="Step 3" look="success">
         <b:inputText label="Summary" value="#{sampleMb.sum}" renderLabel="true"/>
       </b:panel>
     </b:carouselItem>
     <b:carouselControl direction="right" >
         <b:commandButton value="previous step" role="button"
           onclick="$('.wizardPseudoClass').carousel('prev');$('.wizardPseudoClass').carousel('pause'); return false;"
           look="info" />
     </b:carouselControl>
     <b:carouselControl direction="left">
         <b:commandButton value="next step" role="button" style="position:absolute;right:0px" action="#{sampleMb.actionAdd}"        oncomplete="$('.wizardPseudoClass').carousel('next');$('.wizardPseudoClass').carousel('pause'); return false;"
           look="success" ajax="true"/>
     </b:carouselControl>
    </b:carousel>				
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>
```

Managed Bean :

```java
package gov.saglik.tkhk.anket.web.backing.form.rapor;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean(name = "sampleMb")
@ViewScoped
public class SampleManagedBean {
	
	private Integer number1;
	private Integer number2;
	private Integer sum;
	
	public void actionAdd() {
		if (number1 != null && number2 != null){
			sum = number1 + number2;
		}
	}
	
	public Integer getNumber1() {
		return number1;
	}
	public void setNumber1(Integer number1) {
		this.number1 = number1;
	}
	public Integer getNumber2() {
		return number2;
	}
	public void setNumber2(Integer number2) {
		this.number2 = number2;
	}
	public Integer getSum() {
		return sum;
	}
	public void setSum(Integer sum) {
		this.sum = sum;
	}

}
```

Thanks

**Comment by stephanrauh** [comment] 2016-09-12 19:03
Let's have a close look at the "next" button:

```xml
<b:commandButton value="next step" ... 
                                  action="#{sampleMb.actionAdd}"      
                                  oncomplete="$('.wizardPseudoClass').carousel('next');..."
                                  ajax="true"/>
```

* The `action` attribute usually is used to navigate to another page. You can suppress this by returning `null` or by defining the method as a `void` method, but still, it looks suspicious. Better replace it with an `actionListener` or - BootsFaces style :) - by an AJAXified `onclick` handler.
* You've set `ajax="true"` without defining the `update` region. You'd rather define the `update` region to be the inputText containing the result. Otherwise, probably to much is updated. Currently, I don't know the default values, but it might be the entire form.
* I'm not entirely sure when (or if?) I implemented the `oncomplete` handler. Did you already check if it's called at all? I intend to deliver this feature with BootsFaces 1.0, but as far as I remember, it's not part of BootsFaces 0.9.1 or below.
* Also, adding `return false` to the `oncomplete´ handler is probably unnecessary. It may even cause problems. `return false` is needed if you want to suppress the default behavior of the button. But I don't think that's what you want to do in this particular case.

**Comment by stephanrauh** [comment] 2016-09-12 19:04
Please report back if my hints help you. Otherwise the issue remains open simply because I don't know your problem is solved :).

**Comment by yasinkasap** [comment] 2016-09-12 19:51
Hi @stephanrauh,
I changed oncomplete to onclick, and last panel shown but the action method did not called. The command button has role="button" attribute. This effects calling action method or not ?

Thanks.

**Comment by yasinkasap** [comment] 2016-09-13 07:40
I'm trying to both calling action method and showing all panels by next button but one of them doesn't happen.I tried things that you said. I candly request to you, can you try this situation on your environment ?

Thanks.

**Comment by stephanrauh** [comment] 2016-09-13 20:14
Will do :).

**Comment by stephanrauh** [comment] 2016-09-13 20:52
I managed to reproduce your problem with BootsFaces 0.9.2-SNAPSHOT. 

*Analysis:*
First of all, I observe that a click on "next" in the second step of the wizard makes the first step reappear for a fraction of a second.

Looking at the AJAX response, I observe that the entire form is updated. The carousel is part of the form, so it's re-initialized from scratch, which makes the first step of the form appear. The `oncomplete` listener is called, so `...carousel('next')` is called, which shifts the second tag into view again.

**Comment by stephanrauh** [comment] 2016-09-13 21:03
Restricting the update region to the summary input field makes the third carousel item appear as expected:

```xml
     <b:carouselItem style="width:400px;height:230px">
       <b:panel title="Step 3" look="success">
         <b:inputText label="Summary" value="#{issue504Bean.sum}" renderLabel="true" id="summary-id"/>
       </b:panel>
     </b:carouselItem>
...
     <b:carouselControl direction="left">
         <b:commandButton value="next step" role="button" style="position:absolute;right:0px" action="#{issue504Bean.actionAdd}" 
                          oncomplete="console.log('oncomplete');$('.wizardPseudoClass').carousel('next');$('.wizardPseudoClass').carousel('pause'); return false;"
                          update="summary-id"
                          look="success" ajax="true"/>
     </b:carouselControl>
```

**Comment by stephanrauh** [comment] 2016-09-13 21:07
I've committed my solution in the BootsFacesWeb project (https://github.com/TheCoder4eu/BootsFacesWeb, local URL: http://127.0.0.1:8080/BootsFacesWeb/issues/issue504.jsf, URL on our development showcase: http://www3.bootsfaces.net/Showcase/issues/issue504.jsf).

**Comment by stephanrauh** [comment] 2016-09-13 21:11
I've double-checked the solution with BootsFaces-0.9.1. It works flawlessly, too. 

So I'll close this issue, but I keep watching it. If the carousel still doesn't work for you, just tell me, and I'll listen.

Best regards
Stephan

**Closed by stephanrauh** 2016-09-13 21:11 UTC
Labels: User support, Waiting for user answer

**Comment by yasinkasap** [comment] 2016-09-14 09:17
Hi @stephanrauh ,

Thanks for your help. I solved this problem by adding update attribute to next command button and giving an id for summary text field. The action method was called.

Thanks for your help.
