### ISSUE TITLE
[org.apache.myfaces.application.ApplicationImpl] () Undefined component type net.bootsfaces.layout.***

### ISSUE THREAD

**Issue by rayidimurali** [TheCoder4eu/BootsFaces-OSP#198] opened 2015-10-30 17:07 UTC
Hey I am trying to setup bootsfaces in my JSF application, I am seeing below error, can someone please help?

org.apache.myfaces.application.ApplicationImpl Undefined component type net.bootsfaces.layout.Row

at org.apache.myfaces.application.ApplicationImpl.createComponent(ApplicationImpl.java:1437)
at org.apache.myfaces.application.ApplicationImpl.createComponent(ApplicationImpl.java:1405)
at org.jboss.weld.integration.webtier.jsf.ForwardingApplication.createComponent(ForwardingApplication.java:122)
at org.apache.myfaces.view.facelets.tag.jsf.ComponentTagHandlerDelegate.createComponent(ComponentTagHandlerDelegate.java:576)
at org.apache.myfaces.view.facelets.tag.jsf.ComponentTagHandlerDelegate.apply(ComponentTagHandlerDelegate.java:284)
at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:50)
at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:46)
at org.apache.myfaces.view.facelets.tag.ui.DefineHandler.applyDefinition(DefineHandler.java:86)
at org.apache.myfaces.view.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:178)
at org.apache.myfaces.view.facelets.impl.TemplateContextImpl$TemplateManagerImpl.apply(TemplateContextImpl.java:193)
at org.apache.myfaces.view.facelets.impl.TemplateContextImpl.includeDefinition(TemplateContextImpl.java:136)

**Comment by stephanrauh** [comment] 2015-10-30 21:57
You don't happen to use Spring Boot? That won't work. Spring Boots doesn't initialize our library correctly.

**Comment by rayidimurali** [comment] 2015-10-30 22:58
No, we don't use Spring boot. Our application is jboss6 with apache my faces 2.0. Please let me know if you need any other info.

**Comment by stephanrauh** [comment] 2015-10-30 23:04
OK. Actually, I'm puzzled. Let's try to investigate your problem another way. Please check out one of my demo projects, for instance https://github.com/stephanrauh/BootsFaces-Examples/tree/master/TreeAndTable. That's a project I showed to a co-worker of mine just a couple of days ago, so I'm fairly positive it works out of the box. It's a simple Maven project, so I hope you won't have trouble to run it. Once you've managed to do so, replace the Mojarra dependency by MyFaces. If that works, too, try to find out the difference between your project and my demo project.

Oh, and please report back so other developers can benefit, too. Thanks!

**Comment by rayidimurali** [comment] 2015-10-31 13:51
After some more research, I found below error in logs. Do you have any any idea?

2015-10-31 09:19:52,378 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/legacy]] () Exception sending context initialized event to listener instance of class com.sun.faces.config.ConfigureListener: com.sun.faces.config.ConfigurationException: CONFIGURATION FAILED! 
  Source Document: vfs:/data/port9200/appserver/jboss/server/atc/deploy/consumersite-ear.ear/lib/bootsfaces-0.7.0.jar/META-INF/faces-config.xml
  Cause: Class 'net.bootsfaces.render.PaginatorR' is not an instance of 'class javax.faces.render.Renderer'
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:214)

**Comment by stephanrauh** [comment] 2015-10-31 19:29
You seem to have both Apache MyFaces and Oracle Mojarra in your project. Remove one of those dependencies, and things should look better.

**Comment by stephanrauh** [comment] 2015-11-05 23:08
According to http://stackoverflow.com/questions/33443634/undefined-component-type-net-bootsfaces-layout/33524908#33524908, Murali solved the problem by unzipping the content of the jar file. I can't say I understand why this should help, but I'll close this issue because I suspect this issue has reached a dead end. 

@rayidimurali If you provide us a reproducer, I'll gladly re-open this issue.

**Closed by stephanrauh** 2015-11-05 23:08 UTC
Labels: help wanted, User support
