### ISSUE TITLE
navLink iconAwesome doesn't work if header attribute is defined

### ISSUE THREAD

**Issue by georgemoralis** [TheCoder4eu/BootsFaces-OSP#192] opened 2015-10-02 08:05 UTC
For example

```xml
<b:navLink header="Dashboard" iconAwesome="tachometer"/>
```

**Comment by stephanrauh** [comment] 2015-10-05 22:33
It's true - you can render either a header or an icon. 

@TheCoder4eu Riccardo, is this a feature or a bug? I suspect it's possible to fix the bug, but I'm not sure (NavLink.java, line 131+).

**Comment by TheCoder4eu** [comment] 2015-11-13 08:23
Hi,
have a look to the documentation page:
http://www.bootsfaces.net/layout/navLinks.jsf
in the panel
"Attributes of <b:navLink >"
you can read:
 "header : If present, this element is rendered as Header in a menu with the text specifide by this attribute value: all other attributes will be ignored."

So, this is not a bug, but we will try to add a icon to a header in next version.

**Comment by stephanrauh** [comment] 2015-12-30 18:17
@georgemoralis I'd like to mention you in the "kudos" list of the BootsFaces 0.8 announcement post. Is that fine by you?

**Comment by georgemoralis** [comment] 2015-12-30 21:28
sure why not :+1:

**Comment by stephanrauh** [comment] 2015-12-30 22:41
Great! It may be a silly question - but I take it your name it George Moralis? Or is it a nickname?

Just to give you some context: the current draft of the "kudos" section looks like so:

A project like BootsFaces isn’t possible without the help of the community – in other words, without your help. In particular, many developers opened issues on our bug tracker, nudged us into the right direction by asking questions, chatting about us on Twitter or adding code to BootsFaces. I’m sure I’ve forgot many important contributors in my list, but I’d like to try to mention everyone who’s contributed code and agreed to being mentioned. Thanks to: Alexander Hofmeister, Yeray Santana Borges, George Moralis, Lukáš Vasek, Duncan Bloem and countless others. Your contribution matters!

**Comment by georgemoralis** [comment] 2015-12-30 23:15
yah it's my real name

Your kudos draft looking good

**Comment by stephanrauh** [comment] 2016-01-05 21:16
Browsing through the open issue, I just observed this ticket could be closed. According to the documentation, it's simply a matter of fact that navLink headers don't support icons. @georgemoralis and @TheCoder4eu Is this acceptable to you? Or do you think we should add optional icons to headers? And is it technically possible?

**Comment by georgemoralis** [comment] 2016-01-06 10:24
according to bootstrap it is not permitted so it's up to you if you want to add support for it or not

**Comment by stephanrauh** [comment] 2016-01-06 20:19
OK, I'll close the issue. I don't think it's a good idea to be more clever than Bootstrap.

**Closed by stephanrauh** 2016-01-06 20:19 UTC
Labels: enhancement
