### ISSUE TITLE
b:selectMultiMenu always returns an empty string

### ISSUE THREAD

**Issue by atsoares** [TheCoder4eu/BootsFaces-OSP#817] opened 2017-07-12 14:20 UTC
Hi, I'm trying to use the tag selectMultiMenu as the following example:

```xml
<b:selectMultiMenu value="#{vendaEstabelecimentoBean.filtro.idFilialEstabelecimentoString}">
              <f:selectItems 
value="#{vendaEstabelecimentoBean.listaFilial}" 
var="aux" 
 itemValue="#{aux.idFilialEstabelecimento}" 
itemLabel="#{aux.txNomeReduzidoNrSeguranca}" />

</b:selectMultiMenu>
```

I'm trying to use the items selected as a filter, but when I select one item and call the function, it returns an empty string.

When I pass the same value to an input tag, it returns the correct value.

Anyone can help?

**Comment by stephanrauh** [comment] 2017-07-12 20:23
Pues... if you've copied the code snippet from your code, check the value attribute. There's a curly brace missing (`value="#vendaEstabelecimentoBean`).

**Comment by stephanrauh** [comment] 2017-07-12 20:24
BTW, please report back if my answer solved your problem, so I can either close the ticket or investigate more thoroughly. Thanks in advance!

Stephan

**Comment by atsoares** [comment] 2017-07-13 12:02
Hi, thanks for the reply but that is not the problem. 
In my code its correct. 

`<b:selectMultiMenu value="#{vendaEstabelecimentoBean.filtro.idFilialEstabelecimentoString}">
              <f:selectItems value="#{vendaEstabelecimentoBean.listaFilial}" var="aux" itemValue="#{aux.idFilialEstabelecimento}" itemLabel="#{aux.txNomeReduzidoNrSeguranca}" />
            </b:selectMultiMenu>`

and as I said if a use an input tag like:
 `<b:inputText value="#{vendaEstabelecimentoBean.filtro.idFilialEstabelecimentoString}"></b:inputText>`

it works.

**Comment by stephanrauh** [comment] 2017-07-13 21:20
I wonder if it's a data type or data conversion problem. What do your beans look like?

**Comment by atsoares** [comment] 2017-07-26 20:09
Just to let you know that I gave up of this, instead I'm using a <h:selectManyCheckbox> inside of a dropMenu.

**Comment by stephanrauh** [comment] 2017-07-26 21:03
Thank's for reporting back. I'm happy you've found a working solution. Still, I'm sad we couldn't help you with the original problem. I'll close the ticket because I don't know how to help you (because I couldn't reproduce your bug), but I close it reluctantly.

**Closed by stephanrauh** 2017-07-26 21:03 UTC
Labels: User support, Waiting for user answer
