### ISSUE TITLE
Invalid search expression in <b:CommandButton> inside a <b:modal>

### ISSUE THREAD

**Issue by ruanfelisky** [TheCoder4eu/BootsFaces-OSP#861] opened 2017-09-12 17:00 UTC
Hi BootsFaces team!

After upgrading from version 1.1.2 to 1.1.3 the following error is occurring on some forms, when loading the page:

2017-09-12 13:16:15,786 ERROR [com.mesure.util.jsf.JsfExceptionHandler] Erro de sistema: Invalid search expression: colaboradoresTable The subexpression colaboradoresTable doesn't exist, or it can't be resolved. net.bootsfaces.component.commandButton.CommandButton  frmCadastro:j_idt75  Additional information: ID not found: colaboradoresTable search expression: colaboradoresTable

The `<b:commandButton>` existing inside the `<b:modal>` uses the ID of my table `colaboradoresTable` to update it.

I realized that removing `<b:tabView>` and `<b:tab>` the error no longer occurs. So apparently there is something wrong with these components.

My code:

```xml
<script>
	function abrirModalConfirmacao() {
		$('.modal-confirmacao').modal('show');
		return false;
	}
		
	function fecharModalConfirmacao() {
		$('.modal-confirmacao').modal('hide');
		return false;
	}		
</script>

<h:form id="frmCadastro">
	<b:modal id="modal-confirmacao" styleClass="modal-confirmacao" title="Confirmação" size="modal-sm" backdrop="false">
		<p>Confirma a exclusão deste colaborador?</p>
		<f:facet name="footer">
			<b:commandButton value="Ok" oncomplete="javascript:fecharModalConfirmacao()" 
				action="#{cadastroEquipeBean.excluirColaboradorEquipe}"
				process="@this" update="colaboradoresTable mensagens" />										
			<b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
		</f:facet>
	</b:modal> 
			
	<b:container fluid="true">	
		<b:messages id="mensagens" info-class="message-info-hidden" />
		
		<b:tabView content-class="content-tab">
			<b:tab title="Colaborador">		
				<b:dataTable id="colaboradoresTable" value="#{cadastroEquipeBean.equipe.colaboradores}" var="colaborador" customLangUrl="#{resource['/json/pt-br.json']}"
					searching="false" paginated="false"	>					
					<b:dataTableColumn value="#{colaborador.nome}" label="Nome"/>	    		
					<b:dataTableColumn label="" style-class="coluna-acao-1btn" orderable="false">
						<b:navCommandLink oncomplete="javascript:abrirModalConfirmacao()" tooltip="Excluir" process="@this" update="colaboradoresTable" iconAwesome="remove" value="">
							<f:setPropertyActionListener target="#{cadastroEquipeBean.colaboradorEquipe}" value="#{colaborador}" />
						</b:navCommandLink>										
					</b:dataTableColumn>
				</b:dataTable>
			</b:tab>
		</b:tabView>
	</b:container>
</h:form>
```

Please help me, I would like to use version 1.1.3 to make available the new features of `<b:dataTable>` (`excel`, `csv`, `pdf`, `columnVisibility`).

Thank you very much.

**Comment by ruanfelisky** [comment] 2017-09-12 17:15
After removing `colaboradoresTable` the same error occurs for `mensagens`:

2017-09-12 14:09:06,222 ERROR [com.mesure.util.jsf.JsfExceptionHandler] Erro de sistema: Invalid search expression: mensagens The subexpression mensagens doesn't exist, or it can't be resolved. net.bootsfaces.component.commandButton.CommandButton  frmCadastro:j_idt90:j_idt96  Additional information: ID not found: mensagens search expression: mensagens

Again, removing `<b:tabView>` and `<b:tab>` the error no longer occurs.

**Comment by stephanrauh** [comment] 2017-09-12 19:10
I guess that's a side effect of #807. `<b:tab>` now has a client ID, so the old name space is broken. I tried to avoid that, but it proved to be impossible.

Use `update="**:colaboradoresTable` instead.

**Comment by stephanrauh** [comment] 2017-09-12 19:56
I've just copied your source code into my project. Adding the two asterisks solves the bug. But I can't reproduce your second bug. I've removed the datatable but there's no bug concerning the messages. Maybe you've deleted them, too?

**Comment by atsoares** [comment] 2017-09-14 19:23
I've got another problem too with components inside Modals. 

In my case I have a dropButton that closes when I click inside. I've solved it when it's inside the `<body>` but if I use it inside a Modal, it doesn't work.

**Comment by stephanrauh** [comment] 2017-09-14 20:30
@atsoares I'm afraid I don't get your use case. I thought `b:dropButtons` are meant to close, no matter where you click?

**Comment by atsoares** [comment] 2017-09-15 21:01
I'm using it trying to solve this problem #817 like I did before, a `h:selectManyCheckbox` inside of a `b:dropButton` (just to use the button style).  

It works when I use it outside of a div modal, but I think that the reference to the selector is different when we use it inside. Don't know yet how to procede.

Just to explain better, in my case the `b:dropButton` works like a `b:selectMultiMenu`. 

``` 
<b:column>
  <b:dropButton styleClass="filter" style="color: #006099;" value="Tipos de Serviços">

    <b:listLinks>
      <h:selectManyCheckbox value="#{propostaUGBean.filtro.idTipoServicoFiltro}" layout="pageDirection">
        <f:selectItems value="#{lista.getTipoServico('', false)}" var="aux" itemValue="#{aux.value}" itemLabel="#{aux.label}" />
       </h:selectManyCheckbox>
     </b:listLinks>

  </b:dropButton>
</b:column>
```

Using it outside of a modal works perfect, but it should be inside.

**Comment by ruanfelisky** [comment] 2017-09-22 18:53
Hi @stephanrauh 

Adding the two asterisks solves the bug in `colaboradoresTable`, but I still have an error in `<b:messages>`

Erros message: 
javax.faces.FacesException: Invalid search expression: mensagens The subexpression mensagens doesn't exist, or it can't be resolved. net.bootsfaces.component.commandButton.CommandButton  frmCadastro:j_idt91:j_idt97  Additional information: ID not found: mensagens search expression: mensagens

My entire code:
```xml
<ui:composition template="/WEB-INF/template/LayoutPadrao.xhtml"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:o="http://omnifaces.org/ui"
    xmlns:b="http://bootsfaces.net/ui">

    <ui:define name="titulo">Equipes e Setores</ui:define>
    
    <ui:define name="corpo">
        <f:metadata>
			<o:viewParam name="equipe" value="#{cadastroEquipeBean.equipe}" converter="equipeConverter" />
			<f:viewAction action="#{cadastroEquipeBean.inicializar}"></f:viewAction>
		</f:metadata>
		
		<script>
			function abrirModalConfirmacao() {
				$('.modal-confirmacao').modal('show');
				return false;
			}
		
			function fecharModalConfirmacao() {
				$('.modal-confirmacao').modal('hide');
				return false;
			}		
		</script>
		
   	    <h:form id="frmCadastro">
   	    
			<!-- Tela modal para confirmar a exclusão do colaborador -->
			<b:modal id="modal-confirmacao" styleClass="modal-confirmacao" title="Confirmação" size="modal-sm" backdrop="false">
				<p>Confirma a exclusão deste colaborador?</p>
				<f:facet name="footer">
					<b:commandButton value="Ok" oncomplete="javascript:fecharModalConfirmacao()" 
						action="#{cadastroEquipeBean.excluirColaboradorEquipe}"
						process="@this" update="**:colaboradoresTable" />										
					<b:button value="Cancelar" look="primary" dismiss="modal" onclick="return false;" />
				</f:facet>
			</b:modal>    
			   	    
	   		<b:container fluid="true">
	   		
	   		<h3>Cadastro equipes e setores de trabalho</h3>
	   		
	   		<b:messages id="mensagens" info-class="message-info-hidden" />
	   		<p:growl autoUpdate="true" for="message-growl" life="2000" showDetail="true" showSummary="false" />
	    	
	    	<b:focus target="descricao" />
	    	<b:defaultCommand target="gravar" />
	    		    	
	    	<b:panel>
	    		<b:button value="Nova equipe" outcome="/cadastros/CadastroEquipe" look="primary" size="sm" />
	    		<p:spacer width="10"/>
	    		<b:commandButton value="Gravar" id="gravar" action="#{cadastroEquipeBean.salvar}" look="primary" size="sm"
	    			process="@this @(.dados)" update="@form" oncomplete="javascript:configurarMascara();" />	    		
	    		<b:button value="Fechar" outcome="/cadastros/PesquisaEquipes" look="primary" style="float: right" size="sm" />
	    	</b:panel>
	    	
	    	<b:panel>
			<b:row styleClass="dados">
				<b:column span="4">
					<b:inputText label="Descrição Equipe" id="descricao" maxlength="60" value="#{cadastroEquipeBean.equipe.descricao}" fieldSize="sm" required="true" requiredMessage="Descrição Equipe deve ser informada"/>
				</b:column>
			</b:row>
			</b:panel>
			
			<b:tabView content-class="content-tab">
						
			<!-- # COLABORADORES # -->
			<b:tab title="Colaborador">	
				<b:row>
					<b:column span="3">
						<b:selectOneMenu id="selectColaboradores" value="#{cadastroEquipeBean.colaboradorEquipe}" fieldSize="sm">
							<f:selectItem itemLabel="Selecione o colaborador" itemValue="" noSelectionOption="true" />
							<f:selectItems value="#{cadastroEquipeBean.colaboradores}" var="col" itemValue="#{col}" itemLabel="#{col.nome}" />
						</b:selectOneMenu>
					</b:column>											
					<b:column span="2">
						<b:commandButton icon-awesome="plus" size="sm" tooltip="Incluir" style-class="btn-plus"
							 action="#{cadastroEquipeBean.incluirColaboradorEquipe}" process="@this selectColaboradores" update="colaboradoresTable selectColaboradores mensagens"/>
 					</b:column> 					
				</b:row>
				
				<b:dataTable id="colaboradoresTable" value="#{cadastroEquipeBean.equipe.colaboradores}" var="colaborador" customLangUrl="#{resource['/json/pt-br.json']}"
					searching="false" paginated="false"	>
					
		    		<b:dataTableColumn value="#{colaborador.nome}" label="Nome"/>
	    		
			    	<b:dataTableColumn label="" style-class="coluna-acao-1btn" orderable="false">
			    		<b:navCommandLink oncomplete="javascript:abrirModalConfirmacao()" tooltip="Excluir" process="@this" update="colaboradoresTable" iconAwesome="remove" value="">
			    			<f:setPropertyActionListener target="#{cadastroEquipeBean.colaboradorEquipe}" value="#{colaborador}" />
		    			</b:navCommandLink>										
		    		</b:dataTableColumn>
				</b:dataTable>						
			</b:tab>			
			
			</b:tabView>				
			
			</b:container>	
		</h:form>	
    </ui:define>
</ui:composition>
```

Note that I have a `<b:commandButton>` that updates `messages`. If I remove this `<b:commandButton>` the error no longer occurs.

Thanks.

**Comment by ruanfelisky** [comment] 2017-09-22 19:15
Using `frmCadastro:mensagens` solves the bug.

But using `**:mensagens` I got the error:

javax.faces.FacesException: Invalid search expression: **:mensagens The subexpression @findIdRecursively(mensagens) doesn't exist, or it can't be resolved. net.bootsfaces.component.commandButton.CommandButton  frmCadastro:j_idt91:j_idt97  Additional information: Invalid search expression - couldn't find id @findIdRecursively(mensagens). Complete search expression: **:mensagens

So in `<b:modal>` I should use `**:` and others I should use `frmCadastro:` right?

Tks.

**Comment by stephanrauh** [comment] 2017-09-22 20:37
If neither ** nor `@findIdRecursively(mensagems)` works, use `frmCadastro`. In the meantime, we'll examine why `**` doesn't work. BTW, it's just a synonym of `@findIdRecursively()`.

**Comment by ruanfelisky** [comment] 2017-09-23 00:03
Ok so for now I'm gonna use `frmCadastro` when neither `**:` nor `@findIdRecursively(mensagems)` works.

**Comment by stephanrauh** [comment] 2019-08-03 20:16
I'd like to close the issue. Our team has become a lot smaller, so I feel the need to prioritize things.

**Closed by stephanrauh** 2019-08-03 20:16 UTC
Labels: User support, confirmed
