### ISSUE TITLE
Showcase menu out of order?

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#81] opened 2015-04-22 20:58 UTC
Hi Riccardo,

I've received a very detailed error description. Michał Gnatowski can't use the menu of our showcase. Thing is, everything looks fine on my laptop, so I've got no idea what's wrong. Do you have an idea?

Here's what he writes (copied from http://www.beyondjava.net/blog/bootsfaces-0-6-6-easter-edition/):

1.
After clicking “BootsFaces” in the menu there is error:
“NetworkError: 404 Not Found – http://www.bootsfaces.net/index.jsf/index.xhtml”
2.
After clicking “Getting Started”, “Layouts”, “Forms”, etc. in the menu there is no action at all. Only “Examples” works well.
3.
I compared with the page: http://www.angularfaces.net/ – it works well.
4.
It happend just after BootsFaces 0.6.5 was released.
I tested on FF, Chrome, Safari on a few available computers. It always works the same way.

Regards,
Stephan

**Comment by TheCoder4eu** [comment] 2015-04-22 21:40
Hi Stephan,
clicking “BootsFaces” leads to a not found error indeed, I think it is a problem just with the Brand link of the navbar.

The remaining problems are not confirmed: I tested this everywhere , even on a fresh install of Windows with explorer 11 and FF, and averything looks fine.

**Comment by stephanrauh** [comment] 2015-04-22 21:45
I can't imagine anybody writes such a detailed error description without having run into trouble... 
strange.

**Comment by TheCoder4eu** [comment] 2015-04-23 07:25
I think too it is strange, however it is detailed in describing the issues, it is not detailed in stating:
- Operating System(s)
-  versions of the browsers
- if the browser(S) show Javascript errors, if the menus do not activate this might shed a light on what's happening

If we have a chance to reproduce the problem, then we might be able to fix it.

**Comment by TheCoder4eu** [comment] 2015-04-23 07:29
The only guess is that this could be related somehow in using the CombinedResourceHandler of OmniFaces, but it is hard to understand what might fail without further details.

**Comment by MichalGn** [comment] 2015-04-23 12:10
Hi guys,

The person who has the problem is me.

I work on Win7, Firefox 37.0.2. 
I tested also on Chrome, and on all available computers.
I tested event on my tablet Asus Google Nexux 7 with the newest version of Android.
The results are always the same. We cannot use menu on the page www.bootsfaces.net

My steps are
1.
Entering the page www.bootsfaces.net
Errors:
"NetworkError: 404 Not Found - http://www.bootsfaces.net/javax.faces.resource/eNp1kE8LgzAMxT9Rq2W33rbBBt6GF28j66pt8W9iC8I-_Cg6EOpueS-_5JG8qJZuytzkNS7c0YeMdJSRuQ6o9_qCnkzVtYlXQIDEvOMwhCVlS4V2nKPvHjFRrsHMWya4EPzEO9vH9rlvfAtYlBLWamfeQGmSzgPLueD5Ic46TQSNpmRuA-oomNqu_E-8LWo123Cw6RfxHONXvsXofU8.js.jsf?ln=omnifaces.combined&v=1428157483000"
eNp1kE8...7483000
ReferenceError: SyntaxHighlighter is not defined
	

...a></li><li id="j_idt36" name="j_idt36" class=""><a href="/forms/inputText.jsf" r...

www.boo...ces.net (wiersz 15)
ReferenceError: jQuery is not defined
	

...revented()){return}var h=this.dimension();this.$element[h](this.$element[h]())[0...

collaps...?ln=bsf (wiersz 2)
ReferenceError: jQuery is not defined
	

...(m.which==40&&i<o.length-1){i++}if(!~i){i=0}o.eq(i).trigger("focus")};function d...

dropdow...?ln=bsf (wiersz 2)
13:57:52.503 CSI/tbsd_
13:57:52.505 CSI/_tbnd
GET https://apis.google.com/_/scs/apps-static/_/js/k=...kgxffb2wtYxuYd2AClvp7NRg/t=zcms/cb=gapi.loaded_0
	
200 OK
		104ms	
fastbut...5909166 (wiersz 31)
GET https://apis.google.com/_/scs/apps-static/_/js/k=...l1aplFs777k9w0kcwrU_uXRw/t=zcms/cb=gapi.loaded_1
	
200 OK
		108ms	
fastbut...5909166 (wiersz 31)
Strona używa certyfikatu SHA-1 - zalecane jest używanie certyfikatów z algorytmami sygnatur wykorzystującymi funkcje skracania silniejsze niż SHA-1.



2.
Clicking "BootsFaces"
URL: http://www.bootsfaces.net/index.jsf/index.xhtml
On the main page: Not Found
Errors: 
"NetworkError: 404 Not Found - http://www.bootsfaces.net/index.jsf/index.xhtml"


3. 
Clicking "Getting started"
URL: http://www.bootsfaces.net/#
No action, no errors, main page is empty.

How may I help you more?
I attach sceenshot after clicking on "BootsFaces" 

Michał

![bootsfacesmenu](https://cloud.githubusercontent.com/assets/12083433/7296722/7aa43c3a-e9c2-11e4-888b-e3553bfc342c.png)

**Comment by TheCoder4eu** [comment] 2015-04-23 18:05
Hi Michał,
thak you for the precious details, now I can say this is indeed a problem with the CombinedResourceHandler, since you get a not found on a URL generated for the combined resources, however it is quite strange since I also have win 7 and same Firefox version.
This prevents loading jQuery and hence the menus do not work...

I'll investigate on this and let you know ASAP.

**Comment by stephanrauh** [comment] 2015-04-23 19:05
Just a few more ideas:
. I tried to reproduce the problem by deactivating cookies, but didn't succeed.
. You could build a version without the Caching of the CombinedResourceHandler and ask Michal to try again. You could also deactivate the CombinedResourceHandler - the only known negative effects are the missing Glyphicons (apart from the performance penalty, of course).

**Comment by TheCoder4eu** [comment] 2015-04-23 19:13
I just did a couple of checks, IMHO Michał's browser(s) for unknown reasons, still tries to load an old version of the combined resource for Javascript despite being versioned in the URL: 
I suggest to completely clear the cache, close the browser and retry.

**Comment by MichalGn** [comment] 2015-04-23 19:47
Hi Guys,
1.
Please, let me know - can't you reproduce the problem even on your mobile or tablet? I took my wife's mobile which has never seen bootsfaces, and the error is still the same. 
It is hardly to belive, that you can't reproduce it. I have tested on 10+ laptops, few mobiles and a tablet. The error is always the same.

2.
I cleared cache on my FF, and it didn't help :(

3.
After clicking on "BootsFaces" in menu the url is: http://www.bootsfaces.net/index.jsf/index.xhtml
Isn' double index strange? Shouln't be: http://www.bootsfaces.net/index.jsf (without index.xhtml) ?

4.
After clicking on e.g. "Getting started" the url is: http://www.bootsfaces.net/#
What  "#" means ?

5.
As I mentioned before, I compared with www.angularfaces.net, which works ok.
 - After clicking "AngularFaces" the url is: https://www.angularfaces.net/index.jsf
 - After clicking e.g."Getting started", there is no "#" in menu.

Michał

**Comment by stephanrauh** [comment] 2015-04-23 20:28
Hi Michał,

I can answer questions 3 and 4:
3. Some time ago we've changed the URL pattern of the showcase. That's where the double index comes from - we forgot to correct the URL of the link.
4. The # is a minimal link that simply point to the current page. I'm not sure it's really needed - but it's used in every Bootstrap tutorial I've found so far. Technically, the menu items are anchor tags, and the magic of jQuery and Bootstrap converts them into something else.

Regards,
Stephan

**Comment by TheCoder4eu** [comment] 2015-04-23 20:55
4. the # is a fragment : 
http://www.w3.org/TR/html4/intro/intro.html#fragment-uri

**Comment by TheCoder4eu** [comment] 2015-04-23 21:07
Question 1 : I just tried on my nexus 5 with dolphin and chrome, and it works like a charm...
I also tried on my tablet with both browsers, no issue, everything works as expected.

Do you have a DSL connection?

**Comment by TheCoder4eu** [comment] 2015-04-23 21:11
There might be another explanation: do you use some kind of proxy?

**Comment by TheCoder4eu** [comment] 2015-04-23 21:12
A proxy coud have cached an older version of the page or of some resource, the js link you posted is different from the one you should have in your page...

**Comment by MichalGn** [comment] 2015-04-23 21:31
I think I don't use proxy at all, but I am not sure, How may I check it ?
I have no idea. We can connect by skype or teamviewer, and you will see my screen.

I tried once again on my tablet Asus Google Nexus 7 by my WIFI and by GSM card. I confirm:
 - www.angularfaces.net - I can open menu (OK)
 - www.bootsfaces.net - I cann't open menu. (Error)

Michał

**Comment by MichalGn** [comment] 2015-04-23 21:54
May be another question: why only "Examples" work well?
When I click on Examples, there are also errors:

"NetworkError: 404 Not Found - http://www.bootsfaces.net/javax.faces.resource/eNp1kE8LgzAMxT9Rq2W33rbBBt6GF28j66pt8W9iC8I-_Cg6EOpueS-_5JG8qJZuytzkNS7c0YeMdJSRuQ6o9_qCnkzVtYlXQIDEvOMwhCVlS4V2nKPvHjFRrsHMWya4EPzEO9vH9rlvfAtYlBLWamfeQGmSzgPLueD5Ic46TQSNpmRuA-oomNqu_E-8LWo123Cw6RfxHONXvsXofU8.js.jsf?ln=omnifaces.combined&v=1428157483000"
eNp1kE8...7483000
ReferenceError: SyntaxHighlighter is not defined
	

...ton</a></li><li id="j_idt36" name="j_idt36" class=""><a href="/forms/inputText.j...

index.jsf (wiersz 15)
ReferenceError: jQuery is not defined
	

...revented()){return}var h=this.dimension();this.$element[h](this.$element[h]())[0...

collaps...?ln=bsf (wiersz 2)
ReferenceError: jQuery is not defined
	

...(m.which==40&&i<o.length-1){i++}if(!~i){i=0}o.eq(i).trigger("focus")};function d...

dropdow...?ln=bsf (wiersz 2)
![bootsfacesmenu1](https://cloud.githubusercontent.com/assets/12083433/7308343/fb417a6e-ea13-11e4-94d6-81309180de88.png)

**Comment by TheCoder4eu** [comment] 2015-04-24 07:34
I managed to reproduce the problem, it depends on something I suspected but didn't think that could really be the problem, at first: Localization.

If you open Firefox, go to Preferences, click on content and manage the languages (which manipulates what the browser sends as accept-language in the header) putting as first language en (English) when you reload the page everything will work.

It's strange : it works with English, French, German but it doesn't with Polish and even Italian.

I think it might be related with datepicker localization, but I'm not sure now because on the home page the resources for Datepicker should not be loaded, since there is no Datepicker in homepage.

What is sure is that the CombinedResourceHandler fails here for whatever reason does not work correctly whatever the reason is.
I mean, even if it does not find a resource he should create the combined resource anyway!

**Comment by stephanrauh** [comment] 2015-04-24 20:25
Actually, there is an Italian localization of the datepicker :).

As a quick fix, we can exclude the i18n files from the CombinedResourceHandler by setting the target to "body". After that, we should find and fix the error and send a pull request to OmniFaces.

**Comment by stephanrauh** [comment] 2015-04-29 12:40
As it turns out, it's not the datepicker, but AngularFaces which is missing the polish translation of the message bundle. The DatePicker class correctly checks if the localization is there.

**Comment by TheCoder4eu** [comment] 2015-04-29 17:47
Are you going to add it to the message bundle? I had the issue with Italian too, is it missing? Do you need a translation?

Btw, for DatePicker I just picked some of the most used languages, I'll write down the instructions for adding missing ones.

**Comment by stephanrauh** [comment] 2015-04-30 13:14
It seems the datepicker localization didn't work correctly. Instead of reading the user's language preferences, it added every language file that was supported according to the entry in the faces-config.xml. I fixed that. Plus, I added the polish localization file.

![image](https://cloud.githubusercontent.com/assets/3045767/7413360/543a936c-ef4b-11e4-8388-eb459fc9e1ef.png)

![image](https://cloud.githubusercontent.com/assets/3045767/7413379/890267c8-ef4b-11e4-9fab-77536cd979a8.png)

**Comment by stephanrauh** [comment] 2015-04-30 13:17
I also improved the resolution of the AngularFaces message bundle. Both AngularFaces 2.1.4.0+ and BootsFaces 0.6.7+ use the same algorithm now.

**Comment by TheCoder4eu** [comment] 2015-05-23 09:44
Thanks, Stephan.
I suppose we can close this issue, right?

**Comment by stephanrauh** [comment] 2015-05-23 09:52
Hi Riccardo,

Yes, I agree.

CU
Stephan

**Comment by TheCoder4eu** [comment] 2015-05-23 12:29
Thanks, I close.

**Closed by TheCoder4eu** 2015-05-23 12:29 UTC
Labels: bug, confirmed, User support
