### ISSUE TITLE
b:datatable per-column filtering only returns matches in all columns

### ISSUE THREAD

**Issue by susanne69** [TheCoder4eu/BootsFaces-OSP#433] opened 2016-06-22 18:01 UTC
Hi,
I am using Bundle-Version: 0.8.6, Bundle-Date: 20160522-21:44:31.
Entering a filter value in an individual column returns only rows where the value is found in all columns per row.
Example: 
firstname     lastname
John            Dow

If I enter 'o' it returns the row but 'dow' the row disappears.

Is this possible to fix?

Bootsfaces is great :)

**Comment by zhedar** [comment] 2016-06-22 18:58
I currently can't seem to be able to reproduce this. The [Showcase example](http://showcase.bootsfaces.net/forms/DataTable.jsf) (the second) seems to work fine. Does it work for you as well?

Maybe you can provide a small example for us to reproduce.

**Comment by susanne69** [comment] 2016-06-22 19:07
That's a quick response!
I forgot to say that multi-column-search should be true. multi-column-search="true" creates the filter fields for each column. 

What I understood is a specific column is filtered. There is now Showcase for this on your page. They all have multi-column-search not set so basically default value false.

You just need to have one row, my previous example col1: John and col2: Dow. 
Enter dow in the second column and the filter will exclude the row.

Thanks for having a look at this.

**Comment by stephanrauh** [comment] 2016-06-22 19:22
That's the same bug I've encountered this evening. Currently, it puzzles me. The source code we generate looks precisely as the working demo at https://datatables.net/examples/api/multi_filter.html. 

BTW, after your nice words about BootsFaces we simply have to solve the bug for you! :)

**Comment by susanne69** [comment] 2016-06-22 19:27
I feel honoured :)
Thank you!

**Comment by stephanrauh** [comment] 2016-06-22 19:35
More precisely, the search seems to match rows that have the input in every read-only cell. Input fields are ignored.

**Comment by susanne69** [comment] 2016-06-22 20:05
Even worse than I thought ;) Then it's worth fixing it!

**Comment by stephanrauh** [comment] 2016-06-22 20:41
Oh, and I just started to enjoy our nice little chat :). Anyway, I finally managed to wrap my head around it. For some reason, we registered a key listener to every input field in every column. That sounds good, but it was implemented as a double for loop, which means we've registered 25 listeners for a table consisting of five columns. Strange bug - especially because it *seems* to be the same source code as in the documentation.

My current solution is not good, but it'll do for the moment.

**Comment by stephanrauh** [comment] 2016-06-22 20:44
Just in case you want to test the bug fix: I've pushed a new version of BootsFaces 0.9.0-SNAPSHOT to Maven Central. See #369 on how to get it.

**Comment by stephanrauh** [comment] 2016-06-22 20:46
To dos left:
* get the multi-search feature in the header up and running
* replace the current version by a version that also works if there are both footer and header search fields
* add an option to suppress multi-search on a per-column-basis
* document it.

**Comment by susanne69** [comment] 2016-06-24 15:55
I have tried working with BootsFaces 0.9.0-SNAPSHOT and Maven to be prepared when it is fixed :) 
I used the same source code but the per-column filter fields do not show up when setting multi-column-search="true".

**Comment by zhedar** [comment] 2016-06-24 16:15
Hey,
als of 0.9 you also need to set searching="true". Maybe that helps.

**Comment by susanne69** [comment] 2016-06-24 17:22
I have tried searching="true" and searching="false".
multi-column-search="true" does not seem to have an effect. 
The the per-column filter fields do not want to cooperate.

**Comment by stephanrauh** [comment] 2016-06-24 18:03
Nasty fields :). Have a look at http://www3.bootsfaces.net/Showcase/forms/DataTable.jsf (sourcecode at https://github.com/TheCoder4eu/BootsFacesWeb/blob/master/src/main/webapp/forms/DataTable.xhtml). The second demo allows you to switch searching and multi-column-searching on. The table is reloaded on-the-fly by an AJAX request. Hope that helps!

**Comment by susanne69** [comment] 2016-06-24 19:51
My genius his hiding at the moment ... I am sure it will surprise me later when I am done with digesting ;). 
I do not get it. Which build are you using in your Showcase. When I switch the searching value only the general search input appears or disappears. The  per-column filter fields have vacation right now. I cannot see anything wrong in my code. Do you set multi-column-search-position in your Showcase what values would it take? Is multi-column-search dependent on it? Which build are you using in your Showcase?

**Comment by susanne69** [comment] 2016-06-24 20:01
OK. The values of multi-column-search I found, it says with a spelling mistake botton "'top','botton', and 'both'. Default to 'bottom'". ... and set it to something. Look my genius turned up again:
Voilà,! It works. You need to pay me for this :)
It just does not default to anything!

**Comment by susanne69** [comment] 2016-06-24 20:15
... and it works even filtering in the specific column. My John Dow appears now. I meant to call him John Doe but I was so touched by the difficult times of Jones Dow ;)

Thanks you for solving this.

Shall we keep the default value for multi-column-search-position to be solved within this issue?

**Comment by stephanrauh** [comment] 2016-06-24 21:16
Jones Dow :)

**Comment by stephanrauh** [comment] 2016-06-24 21:19
Let's close this ticket and open a new ticket for search buttons above the table. 

@susanne69 THX for your help! I've deactivated the option - I hope that helps other developers avoid the trap I've let you run into. I'm going to publish another developer snapshot to Maven Central in a couple of moments.

**Comment by stephanrauh** [comment] 2016-06-24 21:23
I've uploaded the snapshot and opened a follow-up ticket (#436).

**Closed by stephanrauh** 2016-06-24 21:23 UTC
Labels: bug
