### ISSUE TITLE
DataTable Not work

### ISSUE THREAD

**Issue by YasserTahri** [TheCoder4eu/BootsFaces-OSP#566] opened 2016-11-25 11:16 UTC
please i have used DataTable for dispalying data but it's not working 

any idea please 

Thank you

**Comment by ruanfelisky** [comment] 2016-11-26 12:46
Hi @YasserTahri 

Did you mean date (dd/mm/yyyy) or data (any kind)?
Please post your code for me to try to help you.

**Comment by stephanrauh** [comment] 2016-11-26 22:52
Dear @YasserTahri ,

as much as I'd like to help you, I can't if you don't give us a clue what's wrong. The only thing you told us is that the datatable does not display data. We do not know what your source code looks like.  That could be anything. So I'm going to close this issue. I'll happily reopen it if you provide us a reproducer (i.e. a short program allowing us to reproduce your issue).

Thanks for your understanding
Stephan

**Closed by stephanrauh** 2016-11-26 22:52 UTC
