### ISSUE TITLE
b:dateTimePicker defined on hidden b:modal at start of page

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFaces-OSP#704] opened 2017-04-14 18:08 UTC
I have been struggling with an issue for a while and finally figured it out.  previously i had defined some primefaces `p:dialog` at the top of my page which allowed me to edit events on a calendar.  i switched these for `b:modal` as they work better for mobile screens.  primefaces dialogs cannot scroll.  anyway one of the forms had a `p:calendar` control which i switched for a `b:dateTimePicker`.  Now when i go to a page that uses a `b:dateTimePicker` it renders and functions but will not allow me to click the button to show it.  could this be because it shares the control with the one that is on the modal and because the modal is hidden i cannot see the control?

Update: i moved the `b:modal`definitions to the bottom of the page but the problem still occurs

**Comment by chongma** [comment] 2017-04-14 18:18
further update: it works fine if everything is changed to `p:calendar`

**Comment by stephanrauh** [comment] 2017-04-14 20:32
Would you mind to share a reproducer with us? I.e. a small but complete demo showing the problem? I think that make understanding the problem easier.

**Comment by chongma** [comment] 2017-04-15 18:31
hi i created a test project at https://github.com/chongma/test.  i couldn't get the b:dateTimePicker to render the calendar at all in the example.  not sure why.  so maybe the modal is a red herring

**Comment by stephanrauh** [comment] 2017-04-15 20:22
¡Muchisimas gracias!

I'm not sure I'll manage to have a look at the example this Easter weekend. Stay tuned!

**Comment by chongma** [comment] 2017-04-17 15:25
just checked this with 1.1.0 and it works fine

**Comment by stephanrauh** [comment] 2017-04-18 20:28
That's a bit disturbing, because I can't remember to have fixed the problem :).

**Comment by chongma** [comment] 2017-04-21 14:09
still works on latest 1.1.0-snapshot.  doesn't work with 1.0.2.  shall i close the issue?

**Comment by stephanrauh** [comment] 2017-04-21 17:39
I think you can close this. Maybe our changes of the generated HTML code have solved the problem. However, I'd prefer to know what happened because those bugs have a nasty tendency to pop up again when you're in a hurry :).

**Closed by stephanrauh** 2017-04-21 17:39 UTC
Labels: bug, verifying issue
