### ISSUE TITLE
b:progressBar value Has been set But Still Throw error That Need Value

### ISSUE THREAD

**Issue by goodZhaoliu** [TheCoder4eu/BootsFaces-OSP#898] opened 2017-12-21 03:25 UTC
This is my code：`<b:progressBar value="90"></b:progressBar>`

The error thrown：
Please define the value of the progressbar. It must not be null, nor may it be omitted.
```
viewId=/Pages/WSAPNT4TrainPages2/VbscriptV2.xhtml
location=D:\VMFolder\soft\apache-tomee-plus-7.0.3\webapps\ZLTools\Pages\WSAPNT4TrainPages2\VbscriptV2.xhtml
phaseId=RENDER_RESPONSE(6)

Caused by:
javax.faces.FacesException - Please define the value of the progressbar. It must not be null, nor may it be omitted.
at net.bootsfaces.component.progressBar.ProgressBarRenderer.encodeBegin(ProgressBarRenderer.java:71)
```

**Comment by stephanrauh** [comment] 2017-12-23 13:42
I've copied your code snippet in a JSF page, and it works like charm. Maybe there's a typo in your code? This is the code I used to testing:

```xml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      >
  <h:head>
  </h:head>
  <h:body>
	<b:progressBar value="90"></b:progressBar>
  </h:body>
</html>
```

**Comment by stephanrauh** [comment] 2017-12-26 18:24
I'll close this ticket because I can't reproduce it. We'll reopen the ticket if you send us a working reproducer, ideally as a small GitHub Maven project.

**Closed by stephanrauh** 2017-12-26 18:24 UTC
Labels: verifying issue, Waiting for user answer
