### ISSUE TITLE
Ajax onselect on datatable does not work ?

### ISSUE THREAD

**Issue by traxtech** [TheCoder4eu/BootsFaces-OSP#543] opened 2016-11-06 11:05 UTC
Hi.

I'm having fun with Bootsfaces, but I stumbled on a problem : I can't get ajax onselect on a datatable to work. I created a minimal repo to demonstrate the problem:

https://github.com/traxtech/bfdtselectbug

Maybe I'm doing something wrong ?

**Comment by stephanrauh** [comment] 2016-11-11 20:44
Right now, your repo is really minimal: it doesn't contain code :). But before fixing that, please check out BootsFaces-1.0.0-SNAPSHOT or BootsFaces-0.9.2-SNAPSHOT. See #369 on how to get that preview version.

I've fixed several similar bugs of the data table, so chance are your bug has been fixed, too. Don't forget to report back so we can close this issue.

**Comment by stephanrauh** [comment] 2016-12-04 13:37
This ticket is a duplicate of #570. Please look there to track progress. Cutting a long story short: I believe I've found and solved the bug.

**Closed by stephanrauh** 2016-12-04 13:37 UTC
Labels: bug, Waiting for user answer
