### ISSUE TITLE
Context menu and inline cell edit on double click on datatable - is this feature available on 1.1.3 

### ISSUE THREAD

**Issue by primeO** [TheCoder4eu/BootsFaces-OSP#949] opened 2018-05-31 11:18 UTC
hi , 
    Trying out context menu and inline edit of cell on double click . Is this feature available in bootsfaces 1.1.3 Any suggestions on this how to implement it .

**Comment by stephanrauh** [comment] 2018-05-31 19:06
I don't think we've implemented that yet. 

You should be able to implement in-cell editing yourself by putting both the value and the input field in a cell, setting `selected-items="true"` and make use of the `onselect` callback. We've documented a part of the idea here: https://showcase.bootsfaces.net/forms/DataTable.jsf#inputfields

**Comment by stephanrauh** [comment] 2018-05-31 19:12
As for the context menu: to my surprise, you are only the second asking for this feature. It doesn't seem to be as popular as it used to be. 

I'd implement it using an (initially hidden) navbar and the approach described here: https://www.sitepoint.com/building-custom-right-click-context-menu-javascript/

**Comment by primeO** [comment] 2018-06-01 01:14
Let me give a try stephan. I will let u know

**Comment by stephanrauh** [comment] 2018-06-09 13:15
The context menu is a duplicate of #574.

**Comment by stephanrauh** [comment] 2019-08-03 15:36
Let's close the ticket. It has been open for more than a year.

**Closed by stephanrauh** 2019-08-03 15:36 UTC
Labels: User support, question
