### ISSUE TITLE
Glyphicons resource urls in icons.css

### ISSUE THREAD

**Issue by ryan-bennett** [TheCoder4eu/BootsFaces-OSP#309] opened 2016-02-25 01:17 UTC
Hi There

Had a couple of issues using the icons.css. On review, I noticed that it doesn't use the jsf resource loader. Updating to the following fixed my issue.  This may also fix the need to exclude the icons from the Omnifaces combined resource loader.

@font-face {
	font-family: 'Glyphicons Halflings';
	src: url("#{resource['fonts:glyphicons-halflings-regular.eot']}");
	src: url("#{resource['fonts:glyphicons-halflings-regular.eot']}?#iefix")
		format('embedded-opentype'),
		url("#{resource['fonts:glyphicons-halflings-regular.woff2']}") format('woff2'),
		url("#{resource['fonts:glyphicons-halflings-regular.woff']}") format('woff'),
		url("#{resource['fonts:glyphicons-halflings-regular.ttf']}") format('truetype'),
		url("#{resource['fonts:glyphicons-halflings-regular.svg']}#glyphicons_halflingsregular")
		format('svg');
}

**Comment by TheCoder4eu** [comment] 2016-03-12 15:30
Hi Ryan,
thanks for this contribution, I'll check it ASAP.

**Comment by stephanrauh** [comment] 2016-04-19 21:24
I'll close this issue because it's a duplicate of #328. This issue, in turn, has already been solved.

**Closed by stephanrauh** 2016-04-19 21:24 UTC
Labels: css, enhancement, under consideration

**Comment by stephanrauh** [comment] 2016-04-19 21:26
Just to avoid confusion: AFAIK the #{resource...} approach is currently investigated by one of our team members.
