### ISSUE TITLE
tooltip stills after poll

### ISSUE THREAD

**Issue by VonTalavang** [TheCoder4eu/BootsFaces-OSP#323] opened 2016-03-10 20:45 UTC
when a tooltip is activated...
and the form is refreshed...
the tooltip still... forever... and ever...

**Comment by VonTalavang** [comment] 2016-03-11 14:46
Yes, i guess is because the object is still waiting for the mouse event to remove the tooltip... and if the trigger dissapear... so the message stills there. 
Even if i turn of the monitor !!... (drum joke sound)

**Comment by zhedar** [comment] 2016-04-07 14:58
@VonTalavang  I currently can't reproduce this. Could you provide a minimal snippet?
Here's what I have tried:

    <h:form>
        <b:button value="Hover over me" tooltip="What a nice tooltip!" tooltip-position="auto"/>
       	<b:poll update="@form" />
    </h:form>

Hovering over the button creates the Tooltip, but it doesn't stay after some updates. Also which browser were you using for this to happen? I've encountered several weird tooltip errors, where the browser was to blame.

**Comment by VonTalavang** [comment] 2016-04-07 17:14
chrome.

I remove the tooltips. i dont have code available right now.

**Comment by zhedar** [comment] 2016-04-07 17:23
Thank you for your response.
I've been able to reproduce this in Chrome and Firefox. Safari however doesn't have this issue, that's why I couldn't reproduce it in the first place.

**Comment by VonTalavang** [comment] 2016-04-07 17:27
you are welcome !
thanks for the support

**Comment by zhedar** [comment] 2016-04-07 17:42
This issue may be related to https://github.com/twbs/bootstrap/issues/3084, which recommends to manually hide the tooltip on ajax actions (which remove components, which in turn could be triggered by JSF in this case). My knowledge of JSF's internal ajax behaviour isn't that great yet, so maybe I'm on the wrong path there.

However, manually looking for tooltips and destroying them on ajax requests isn't an option in my opinion, it's just too much overhead in case of frequent ajax requests for such a rare use case. Also you would hide tooltip immediately on every ajax request, which is a negative side effect.

Maybe there might be other hacks for this, that would be applicable though (see referenced bootstrap issue). 
Any thought on that?

**Comment by stephanrauh** [comment] 2016-04-07 18:58
Yes, the problem is a fairly common problem with AJAX request. It includes a lot of components - tooltips, popovers, maybe even modal dialogs. Sometimes you don't even need AJAX to run into problems. A simple tooltip on each row of a datatable causes problems if the datatable has a paginator, sort buttons or a "search" field. I'd suggest to simply hide every popup and every tooltip on every AJAX request.

**Comment by stephanrauh** [comment] 2016-04-21 21:30
Also see #220. Please close #220 when you close this issue.

**Comment by zhedar** [comment] 2016-04-21 21:32
#220 is already in the commit hook of 1ab869b, so it should be automatically closed when #347 is merged into master.

**Closed** 2016-04-28 19:28 UTC
Labels: bug
