### ISSUE TITLE
Blank documentation pages

### ISSUE THREAD

**Issue by OleHusgaard** [TheCoder4eu/BootsFaces-OSP#1139] opened 2020-05-30 18:13 UTC
If I go to https://showcase.bootsfaces.net/ and click on either "Grid system", "Search expressions", "NavLink" or "Label, I am shown a blank page (except for the header).

I tried this in recent versions of both Chrome and Firefox. Other documentation pages seem to be fine.

A few weeks ago these documentation pages were shown fine.

**Comment by stephanrauh** [comment] 2020-05-30 20:39
I could restart the server, but that means we're loosing the log files. So I'd like to point you to our backup showcase at https://showcase.bootsfaces.pecer.de/. I hope that gives us an opportunity to find the cause of the weird crashes. FWIW, I doubt it has anything to do with JSF.

**Comment by OleHusgaard** [comment] 2020-05-30 23:12
Thank you very much. I will use your backup showcase until this issue is closed.
And thank you for this great framework, and your good work on it.

**Comment by geopossachs** [comment] 2020-08-14 19:08
the have problems with the showcase in the last time, so we close this issue with the same topic  -> https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1150

**Closed by geopossachs** 2020-08-14 19:08 UTC
Labels: duplicate
